export default [
    { id: 1, answer: "Web development", is_correct: 1, question_id: 1 },
    { id: 2, answer: "Data Science", is_correct: 0, question_id: 1 },
    { id: 3, answer: "Number", is_correct: 1, question_id: 2 },
    { id: 4, answer: "Character", is_correct: 0, question_id: 2 },
    { id: 5, answer: "parseInt()", is_correct: 1, question_id: 3 },
    { id: 6, answer: "parseFloat()", is_correct: 0, question_id: 3 },
    { id: 7, answer: "True", is_correct: 1, question_id: 4 },
    { id: 8, answer: "False", is_correct: 0, question_id: 4 },
    { id: 9, answer: "let", is_correct: 1, question_id: 5 },
    { id: 10, answer: "varname", is_correct: 0, question_id: 5 },
    { id: 11, answer: "Data Science and Machine Learning", is_correct: 1, question_id: 6 },
    { id: 12, answer: "Web development", is_correct: 0, question_id: 6 },
    { id: 13, answer: "def", is_correct: 1, question_id: 7 },
    { id: 14, answer: "function", is_correct: 0, question_id: 7 },
    { id: 15, answer: "True", is_correct: 1, question_id: 8 },
    { id: 16, answer: "False", is_correct: 0, question_id: 8 },
    { id: 17, answer: "List", is_correct: 1, question_id: 9 },
    { id: 18, answer: "Class", is_correct: 0, question_id: 9 },
    { id: 19, answer: "Pandas", is_correct: 1, question_id: 10 },
    { id: 20, answer: "Django", is_correct: 0, question_id: 10 },
    { id: 21, answer: "class", is_correct: 1, question_id: 11 },
    { id: 22, answer: "new", is_correct: 0, question_id: 11 },
    { id: 23, answer: "Java Virtual Machine", is_correct: 1, question_id: 12 },
    { id: 24, answer: "Java Vendor Module", is_correct: 0, question_id: 12 },
    { id: 25, answer: "False", is_correct: 1, question_id: 13 },
    { id: 26, answer: "True", is_correct: 0, question_id: 13 },
    { id: 27, answer: "main()", is_correct: 1, question_id: 14 },
    { id: 28, answer: "start()", is_correct: 0, question_id: 14 },
    { id: 29, answer: "Class", is_correct: 1, question_id: 15 },
    { id: 30, answer: "Object", is_correct: 0, question_id: 15 },
    { id: 31, answer: "Increment", is_correct: 1, question_id: 16 },
    { id: 32, answer: "Decrement", is_correct: 0, question_id: 16 },
    { id: 33, answer: "Garbage collection", is_correct: 1, question_id: 17 },
    { id: 34, answer: "Operator overloading", is_correct: 0, question_id: 17 },
    { id: 35, answer: "True", is_correct: 1, question_id: 18 },
    { id: 36, answer: "False", is_correct: 0, question_id: 18 },
    { id: 37, answer: "->", is_correct: 1, question_id: 19 },
    { id: 38, answer: ".", is_correct: 0, question_id: 19 },
    { id: 39, answer: "for", is_correct: 1, question_id: 20 },
    { id: 40, answer: "loop", is_correct: 0, question_id: 20 },
    { id: 41, answer: "void", is_correct: 1, question_id: 21 },
    { id: 42, answer: "def", is_correct: 0, question_id: 21 },
    { id: 43, answer: "True", is_correct: 1, question_id: 22 },
    { id: 44, answer: "False", is_correct: 0, question_id: 22 },
    { id: 45, answer: "int", is_correct: 1, question_id: 23 },
    { id: 46, answer: "String", is_correct: 0, question_id: 23 },
    { id: 47, answer: "const", is_correct: 1, question_id: 24 },
    { id: 48, answer: "define", is_correct: 0, question_id: 24 },
    { id: 49, answer: ".NET", is_correct: 1, question_id: 25 },
    { id: 50, answer: "Laravel", is_correct: 0, question_id: 25 },
    { id: 51, answer: "def", is_correct: 1, question_id: 26 },
    { id: 52, answer: "method", is_correct: 0, question_id: 26 },
    { id: 53, answer: "True", is_correct: 1, question_id: 27 },
    { id: 54, answer: "False", is_correct: 0, question_id: 27 },
    { id: 55, answer: "@", is_correct: 1, question_id: 28 },
    { id: 56, answer: "$", is_correct: 0, question_id: 28 },
    { id: 57, answer: "Rails", is_correct: 1, question_id: 29 },
    { id: 58, answer: "Flask", is_correct: 0, question_id: 29 },
    { id: 59, answer: "RubyGems", is_correct: 1, question_id: 30 },
    { id: 60, answer: "Pip", is_correct: 0, question_id: 30 },
    { id: 61, answer: "SELECT", is_correct: 1, question_id: 31 },
    { id: 62, answer: "FETCH", is_correct: 0, question_id: 31 },
    { id: 63, answer: "False", is_correct: 1, question_id: 32 },
    { id: 64, answer: "True", is_correct: 0, question_id: 32 },
    { id: 65, answer: "UPDATE", is_correct: 1, question_id: 33 },
    { id: 66, answer: "MODIFY", is_correct: 0, question_id: 33 },
    { id: 67, answer: "Structured Query Language", is_correct: 1, question_id: 34 },
    { id: 68, answer: "Sequential Query Language", is_correct: 0, question_id: 34 },
    { id: 69, answer: "WHERE", is_correct: 1, question_id: 35 },
    { id: 70, answer: "FILTER", is_correct: 0, question_id: 35 },
    { id: 71, answer: "NoSQL", is_correct: 1, question_id: 36 },
    { id: 72, answer: "Relational", is_correct: 0, question_id: 36 },
    { id: 73, answer: "Binary JSON", is_correct: 1, question_id: 37 },
    { id: 74, answer: "Big JSON", is_correct: 0, question_id: 37 },
    { id: 75, answer: "True", is_correct: 1, question_id: 38 },
    { id: 76, answer: "False", is_correct: 0, question_id: 38 },
    { id: 77, answer: "insertOne()", is_correct: 1, question_id: 39 },
    { id: 78, answer: "addDocument()", is_correct: 0, question_id: 39 },
    { id: 79, answer: "27017", is_correct: 1, question_id: 40 },
    { id: 80, answer: "8080", is_correct: 0, question_id: 40 },
    { id: 81, answer: "SQL:1999", is_correct: 1, question_id: 41 },
    { id: 82, answer: "SQL:2016", is_correct: 0, question_id: 41 },
    { id: 83, answer: "True", is_correct: 1, question_id: 42 },
    { id: 84, answer: "False", is_correct: 0, question_id: 42 },
    { id: 85, answer: "CREATE DATABASE", is_correct: 1, question_id: 43 },
    { id: 86, answer: "NEW DATABASE", is_correct: 0, question_id: 43 },
    { id: 87, answer: "B-Tree", is_correct: 1, question_id: 44 },
    { id: 88, answer: "Hash Indexing", is_correct: 0, question_id: 44 },
    { id: 89, answer: "C", is_correct: 1, question_id: 45 },
    { id: 90, answer: "Python", is_correct: 0, question_id: 45 },
    { id: 91, answer: "Oracle Corporation", is_correct: 1, question_id: 46 },
    { id: 92, answer: "Microsoft", is_correct: 0, question_id: 46 },
    { id: 93, answer: "InnoDB", is_correct: 1, question_id: 47 },
    { id: 94, answer: "MyISAM", is_correct: 0, question_id: 47 },
    { id: 95, answer: "True", is_correct: 1, question_id: 48 },
    { id: 96, answer: "False", is_correct: 0, question_id: 48 },
    { id: 97, answer: "SHOW DATABASES", is_correct: 1, question_id: 49 },
    { id: 98, answer: "LIST DATABASES", is_correct: 0, question_id: 49 },
    { id: 99, answer: "65535", is_correct: 1, question_id: 50 },
    { id: 100, answer: "255", is_correct: 0, question_id: 50 },
    { id: 101, answer: "In-memory key-value store", is_correct: 1, question_id: 51 },
    { id: 102, answer: "Document-based store", is_correct: 0, question_id: 51 },
    { id: 103, answer: "Remote Dictionary Server", is_correct: 1, question_id: 52 },
    { id: 104, answer: "Reliable Data Store", is_correct: 0, question_id: 52 },
    { id: 105, answer: "True", is_correct: 1, question_id: 53 },
    { id: 106, answer: "False", is_correct: 0, question_id: 53 },
    { id: 107, answer: "SET", is_correct: 1, question_id: 54 },
    { id: 108, answer: "INSERT", is_correct: 0, question_id: 54 },
    { id: 109, answer: "Graph", is_correct: 1, question_id: 55 },
    { id: 110, answer: "List", is_correct: 0, question_id: 55 },
    { id: 111, answer: "True", is_correct: 1, question_id: 56 },
    { id: 112, answer: "False", is_correct: 0, question_id: 56 },
    { id: 113, answer: ".db", is_correct: 1, question_id: 57 },
    { id: 114, answer: ".sqlite", is_correct: 0, question_id: 57 },
    { id: 115, answer: "140TB", is_correct: 1, question_id: 58 },
    { id: 116, answer: "1TB", is_correct: 0, question_id: 58 },
    { id: 117, answer: ".open", is_correct: 1, question_id: 59 },
    { id: 118, answer: ".start", is_correct: 0, question_id: 59 },
    { id: 119, answer: "COUNT(*)", is_correct: 1, question_id: 60 },
    { id: 120, answer: "TOTAL()", is_correct: 0, question_id: 60 },
    { id: 121, answer: "Facebook", is_correct: 1, question_id: 61 },
    { id: 122, answer: "Google", is_correct: 0, question_id: 61 },
    { id: 123, answer: "Building user interfaces", is_correct: 1, question_id: 62 },
    { id: 124, answer: "Database management", is_correct: 0, question_id: 62 },
    { id: 125, answer: "False", is_correct: 1, question_id: 63 },
    { id: 126, answer: "True", is_correct: 0, question_id: 63 },
    { id: 127, answer: "class", is_correct: 1, question_id: 64 },
    { id: 128, answer: "function", is_correct: 0, question_id: 64 },
    { id: 129, answer: "JavaScript XML", is_correct: 1, question_id: 65 },
    { id: 130, answer: "JavaScript Extension", is_correct: 0, question_id: 65 },
    { id: 131, answer: "Reactive data binding", is_correct: 1, question_id: 66 },
    { id: 132, answer: "REST API support", is_correct: 0, question_id: 66 },
    { id: 133, answer: "vue create", is_correct: 1, question_id: 67 },
    { id: 134, answer: "npm init vue", is_correct: 0, question_id: 67 },
    { id: 135, answer: "False", is_correct: 1, question_id: 68 },
    { id: 136, answer: "True", is_correct: 0, question_id: 68 },
    { id: 137, answer: "{{ }}", is_correct: 1, question_id: 69 },
    { id: 138, answer: "%% %%", is_correct: 0, question_id: 69 },
    { id: 139, answer: "Evan You", is_correct: 1, question_id: 70 },
    { id: 140, answer: "Brendan Eich", is_correct: 0, question_id: 70 },
    { id: 141, answer: "Google", is_correct: 1, question_id: 71 },
    { id: 142, answer: "Microsoft", is_correct: 0, question_id: 71 },
    { id: 143, answer: "TypeScript", is_correct: 1, question_id: 72 },
    { id: 144, answer: "JavaScript", is_correct: 0, question_id: 72 },
    { id: 145, answer: "True", is_correct: 1, question_id: 73 },
    { id: 146, answer: "False", is_correct: 0, question_id: 73 },
    { id: 147, answer: "*ngFor", is_correct: 1, question_id: 74 },
    { id: 148, answer: "*ngLoop", is_correct: 0, question_id: 74 },
    { id: 149, answer: "Components", is_correct: 1, question_id: 75 },
    { id: 150, answer: "Modules", is_correct: 0, question_id: 75 },
    { id: 151, answer: "Svelte compiles at build time", is_correct: 1, question_id: 76 },
    { id: 152, answer: "Svelte does not use a virtual DOM", is_correct: 0, question_id: 76 },
    { id: 153, answer: "npx degit sveltejs/template", is_correct: 1, question_id: 77 },
    { id: 154, answer: "npm init svelte", is_correct: 0, question_id: 77 },
    { id: 155, answer: "False", is_correct: 1, question_id: 78 },
    { id: 156, answer: "True", is_correct: 0, question_id: 78 },
    { id: 157, answer: "Rich Harris", is_correct: 1, question_id: 79 },
    { id: 158, answer: "Evan You", is_correct: 0, question_id: 79 },
    { id: 159, answer: "{#each}", is_correct: 1, question_id: 80 },
    { id: 160, answer: "{% for %}", is_correct: 0, question_id: 80 },
    { id: 161, answer: "Twitter", is_correct: 1, question_id: 81 },
    { id: 162, answer: "Google", is_correct: 0, question_id: 81 },
    { id: 163, answer: "To create responsive and mobile-first websites", is_correct: 1, question_id: 82 },
    { id: 164, answer: "To manage databases", is_correct: 0, question_id: 82 },
    { id: 165, answer: "True", is_correct: 1, question_id: 83 },
    { id: 166, answer: "False", is_correct: 0, question_id: 83 },
    { id: 167, answer: "container", is_correct: 0, question_id: 84 },
    { id: 168, answer: "row", is_correct: 1, question_id: 84 },
    { id: 169, answer: "Sass", is_correct: 1, question_id: 85 },
    { id: 170, answer: "Stylus", is_correct: 0, question_id: 85 },
    { id: 171, answer: "Cross-browser compatibility", is_correct: 1, question_id: 86 },
    { id: 172, answer: "Improved security", is_correct: 0, question_id: 86 },
    { id: 173, answer: "$", is_correct: 1, question_id: 87 },
    { id: 174, answer: "&", is_correct: 0, question_id: 87 },
    { id: 175, answer: "True", is_correct: 1, question_id: 88 },
    { id: 176, answer: "False", is_correct: 0, question_id: 88 },
    { id: 177, answer: ".hide()", is_correct: 1, question_id: 89 },
    { id: 178, answer: ".invisible()", is_correct: 0, question_id: 89 },
    { id: 179, answer: "$.ajax()", is_correct: 1, question_id: 90 },
    { id: 180, answer: "$.request()", is_correct: 0, question_id: 90 },
    { id: 181, answer: "Server-side scripting", is_correct: 1, question_id: 91 },
    { id: 182, answer: "Client-side rendering", is_correct: 0, question_id: 91 },
    { id: 183, answer: "fs", is_correct: 1, question_id: 92 },
    { id: 184, answer: "jQuery", is_correct: 0, question_id: 92 },
    { id: 185, answer: "True", is_correct: 1, question_id: 93 },
    { id: 186, answer: "False", is_correct: 0, question_id: 93 },
    { id: 187, answer: "npm install", is_correct: 1, question_id: 94 },
    { id: 188, answer: "node install", is_correct: 0, question_id: 94 },
    { id: 189, answer: "npm", is_correct: 1, question_id: 95 },
    { id: 190, answer: "pip", is_correct: 0, question_id: 95 },
    { id: 191, answer: "Web framework", is_correct: 1, question_id: 96 },
    { id: 192, answer: "Machine learning framework", is_correct: 0, question_id: 96 },
    { id: 193, answer: "Python", is_correct: 1, question_id: 97 },
    { id: 194, answer: "JavaScript", is_correct: 0, question_id: 97 },
    { id: 195, answer: "True", is_correct: 0, question_id: 98 },
    { id: 196, answer: "False", is_correct: 1, question_id: 98 },
    { id: 197, answer: "django-admin startproject", is_correct: 1, question_id: 99 },
    { id: 198, answer: "python manage.py startproject", is_correct: 0, question_id: 99 },
    { id: 199, answer: "To map database tables to Python objects", is_correct: 1, question_id: 100 },
    { id: 200, answer: "To manage static files", is_correct: 0, question_id: 100 },
    { id: 201, answer: "To simplify the creation of stand-alone Spring applications", is_correct: 1, question_id: 101 },
    { id: 202, answer: "To manage database connections", is_correct: 0, question_id: 101 },
    { id: 203, answer: "YAML", is_correct: 1, question_id: 102 },
    { id: 204, answer: "XML", is_correct: 0, question_id: 102 },
    { id: 205, answer: "True", is_correct: 1, question_id: 103 },
    { id: 206, answer: "False", is_correct: 0, question_id: 103 },
    { id: 207, answer: "@SpringBootApplication", is_correct: 1, question_id: 104 },
    { id: 208, answer: "@EnableAutoConfiguration", is_correct: 0, question_id: 104 },
    { id: 209, answer: "Tomcat", is_correct: 1, question_id: 105 },
    { id: 210, answer: "Jetty", is_correct: 0, question_id: 105 },
    { id: 211, answer: "Building web applications and APIs", is_correct: 1, question_id: 106 },
    { id: 212, answer: "Managing databases", is_correct: 0, question_id: 106 },
    { id: 213, answer: ".get()", is_correct: 1, question_id: 107 },
    { id: 214, answer: ".post()", is_correct: 0, question_id: 107 },
    { id: 215, answer: "True", is_correct: 1, question_id: 108 },
    { id: 216, answer: "False", is_correct: 0, question_id: 108 },
    { id: 217, answer: "response", is_correct: 1, question_id: 109 },
    { id: 218, answer: "data", is_correct: 0, question_id: 109 },
    { id: 219, answer: "node app.js", is_correct: 1, question_id: 110 },
    { id: 220, answer: "express start", is_correct: 0, question_id: 110 },
    { id: 221, answer: "Convention over Configuration", is_correct: 1, question_id: 111 },
    { id: 222, answer: "Code first", is_correct: 0, question_id: 111 },
    { id: 223, answer: "Ruby", is_correct: 1, question_id: 112 },
    { id: 224, answer: "Python", is_correct: 0, question_id: 112 },
    { id: 225, answer: "True", is_correct: 1, question_id: 113 },
    { id: 226, answer: "False", is_correct: 0, question_id: 113 },
    { id: 227, answer: "rails new projectname", is_correct: 1, question_id: 114 },
    { id: 228, answer: "rails create projectname", is_correct: 0, question_id: 114 },
    { id: 229, answer: "It is the Object-Relational Mapping (ORM) tool", is_correct: 1, question_id: 115 },
    { id: 230, answer: "It is the routing module", is_correct: 0, question_id: 115 },
    { id: 231, answer: "A web framework", is_correct: 1, question_id: 116 },
    { id: 232, answer: "A machine learning framework", is_correct: 0, question_id: 116 },
    { id: 233, answer: "Python", is_correct: 1, question_id: 117 },
    { id: 234, answer: "JavaScript", is_correct: 0, question_id: 117 },
    { id: 235, answer: "True", is_correct: 1, question_id: 118 },
    { id: 236, answer: "False", is_correct: 0, question_id: 118 },
    { id: 237, answer: "flask run", is_correct: 1, question_id: 119 },
    { id: 238, answer: "python manage.py runserver", is_correct: 0, question_id: 119 },
    { id: 239, answer: "Jinja2", is_correct: 1, question_id: 120 },
    { id: 240, answer: "EJS", is_correct: 0, question_id: 120 },
    { id: 241, answer: "Version control", is_correct: 1, question_id: 121 },
    { id: 242, answer: "Dependency management", is_correct: 0, question_id: 121 },
    { id: 243, answer: "git status", is_correct: 1, question_id: 122 },
    { id: 244, answer: "git check", is_correct: 0, question_id: 122 },
    { id: 245, answer: "True", is_correct: 1, question_id: 123 },
    { id: 246, answer: "False", is_correct: 0, question_id: 123 },
    { id: 247, answer: "git clone", is_correct: 1, question_id: 124 },
    { id: 248, answer: "git fetch", is_correct: 0, question_id: 124 },
    { id: 249, answer: ".gitignore", is_correct: 1, question_id: 125 },
    { id: 250, answer: "gitignore.txt", is_correct: 0, question_id: 125 },
    { id: 251, answer: "Hosting Git repositories", is_correct: 1, question_id: 126 },
    { id: 252, answer: "File versioning", is_correct: 0, question_id: 126 },
    { id: 253, answer: "YAML file", is_correct: 1, question_id: 127 },
    { id: 254, answer: "JSON file", is_correct: 0, question_id: 127 },
    { id: 255, answer: "True", is_correct: 1, question_id: 128 },
    { id: 256, answer: "False", is_correct: 0, question_id: 128 },
    { id: 257, answer: "Issues", is_correct: 1, question_id: 129 },
    { id: 258, answer: "Commits", is_correct: 0, question_id: 129 },
    { id: 259, answer: "git push", is_correct: 1, question_id: 130 },
    { id: 260, answer: "git commit", is_correct: 0, question_id: 130 },
    { id: 261, answer: "Hosting Git repositories", is_correct: 1, question_id: 131 },
    { id: 262, answer: "Project management", is_correct: 0, question_id: 131 },
    { id: 263, answer: "GitLab CI/CD", is_correct: 1, question_id: 132 },
    { id: 264, answer: "GitLab Issues", is_correct: 0, question_id: 132 },
    { id: 265, answer: "False", is_correct: 1, question_id: 133 },
    { id: 266, answer: "True", is_correct: 0, question_id: 133 },
    { id: 267, answer: "git clone", is_correct: 1, question_id: 134 },
    { id: 268, answer: "git pull", is_correct: 0, question_id: 134 },
    { id: 269, answer: "To execute jobs defined in GitLab CI pipelines", is_correct: 1, question_id: 135 },
    { id: 270, answer: "To track Git commits", is_correct: 0, question_id: 135 },
    { id: 271, answer: "Hosting Git repositories", is_correct: 1, question_id: 136 },
    { id: 272, answer: "Task management", is_correct: 0, question_id: 136 },
    { id: 273, answer: "Mercurial", is_correct: 1, question_id: 137 },
    { id: 274, answer: "Subversion", is_correct: 0, question_id: 137 },
    { id: 275, answer: "True", is_correct: 1, question_id: 138 },
    { id: 276, answer: "False", is_correct: 0, question_id: 138 },
    { id: 277, answer: "CI/CD for builds and deployments", is_correct: 1, question_id: 139 },
    { id: 278, answer: "Code review", is_correct: 0, question_id: 139 },
    { id: 279, answer: "git fetch", is_correct: 1, question_id: 140 },
    { id: 280, answer: "git clone", is_correct: 0, question_id: 140 },
    { id: 281, answer: "Version control", is_correct: 1, question_id: 141 },
    { id: 282, answer: "Dependency management", is_correct: 0, question_id: 141 },
    { id: 283, answer: "Subversion", is_correct: 1, question_id: 142 },
    { id: 284, answer: "Source Version Network", is_correct: 0, question_id: 142 },
    { id: 285, answer: "False", is_correct: 1, question_id: 143 },
    { id: 286, answer: "True", is_correct: 0, question_id: 143 },
    { id: 287, answer: "svn checkout", is_correct: 1, question_id: 144 },
    { id: 288, answer: "svn clone", is_correct: 0, question_id: 144 },
    { id: 289, answer: "By unique revision numbers", is_correct: 1, question_id: 145 },
    { id: 290, answer: "By commit hashes", is_correct: 0, question_id: 145 },
    { id: 291, answer: "Version control", is_correct: 1, question_id: 146 },
    { id: 292, answer: "Continuous integration", is_correct: 0, question_id: 146 },
    { id: 293, answer: "hg clone", is_correct: 1, question_id: 147 },
    { id: 294, answer: "git clone", is_correct: 0, question_id: 147 },
    { id: 295, answer: "True", is_correct: 1, question_id: 148 },
    { id: 296, answer: "False", is_correct: 0, question_id: 148 },
    { id: 297, answer: ".hgignore", is_correct: 1, question_id: 149 },
    { id: 298, answer: ".gitignore", is_correct: 0, question_id: 149 },
    { id: 299, answer: "hg commit", is_correct: 1, question_id: 150 },
    { id: 300, answer: "git commit", is_correct: 0, question_id: 150 },
    { id: 301, answer: "Delivering working software frequently", is_correct: 1, question_id: 151 },
    { id: 302, answer: "Writing comprehensive documentation", is_correct: 0, question_id: 151 },
    { id: 303, answer: "True", is_correct: 1, question_id: 152 },
    { id: 304, answer: "False", is_correct: 0, question_id: 152 },
    { id: 305, answer: "Customer collaboration", is_correct: 1, question_id: 153 },
    { id: 306, answer: "Contract negotiation", is_correct: 0, question_id: 153 },
    { id: 307, answer: "Incremental and iterative releases", is_correct: 1, question_id: 154 },
    { id: 308, answer: "Single large release", is_correct: 0, question_id: 154 },
    { id: 309, answer: "True", is_correct: 1, question_id: 155 },
    { id: 310, answer: "False", is_correct: 0, question_id: 155 },
    { id: 311, answer: "Maximizing product value", is_correct: 1, question_id: 156 },
    { id: 312, answer: "Managing the development team", is_correct: 0, question_id: 156 },
    { id: 313, answer: "True", is_correct: 1, question_id: 157 },
    { id: 314, answer: "False", is_correct: 0, question_id: 157 },
    { id: 315, answer: "A short meeting to discuss progress", is_correct: 1, question_id: 158 },
    { id: 316, answer: "A sprint planning session", is_correct: 0, question_id: 158 },
    { id: 317, answer: "Product Backlog", is_correct: 1, question_id: 159 },
    { id: 318, answer: "Sprint Goal", is_correct: 0, question_id: 159 },
    { id: 319, answer: "Facilitates Scrum processes", is_correct: 1, question_id: 160 },
    { id: 320, answer: "Leads the development team", is_correct: 0, question_id: 160 },
    { id: 321, answer: "To visualize work", is_correct: 1, question_id: 161 },
    { id: 322, answer: "To assign tasks to team members", is_correct: 0, question_id: 161 },
    { id: 323, answer: "True", is_correct: 1, question_id: 162 },
    { id: 324, answer: "False", is_correct: 0, question_id: 162 },
    { id: 325, answer: "Continuous delivery", is_correct: 1, question_id: 163 },
    { id: 326, answer: "Time-boxed sprints", is_correct: 0, question_id: 163 },
    { id: 327, answer: "Kanban is flow-based, Scrum is iteration-based", is_correct: 1, question_id: 164 },
    { id: 328, answer: "Kanban uses sprints, Scrum does not", is_correct: 0, question_id: 164 },
    { id: 329, answer: "False", is_correct: 1, question_id: 165 },
    { id: 330, answer: "True", is_correct: 0, question_id: 165 },
    { id: 331, answer: "To detect issues early", is_correct: 1, question_id: 166 },
    { id: 332, answer: "To reduce testing", is_correct: 0, question_id: 166 },
    { id: 333, answer: "True", is_correct: 1, question_id: 167 },
    { id: 334, answer: "False", is_correct: 0, question_id: 167 },
    { id: 335, answer: "Jenkins", is_correct: 1, question_id: 168 },
    { id: 336, answer: "VS Code", is_correct: 0, question_id: 168 },
    { id: 337, answer: "It automates code integration and testing", is_correct: 1, question_id: 169 },
    { id: 338, answer: "It reduces the need for code reviews", is_correct: 0, question_id: 169 },
    { id: 339, answer: "True", is_correct: 1, question_id: 170 },
    { id: 340, answer: "False", is_correct: 0, question_id: 170 },
    { id: 341, answer: "Writing tests before code", is_correct: 1, question_id: 171 },
    { id: 342, answer: "Writing code before tests", is_correct: 0, question_id: 171 },
    { id: 343, answer: "True", is_correct: 1, question_id: 172 },
    { id: 344, answer: "False", is_correct: 0, question_id: 172 },
    { id: 345, answer: "Write a failing test", is_correct: 1, question_id: 173 },
    { id: 346, answer: "Refactor the code", is_correct: 0, question_id: 173 },
    { id: 347, answer: "Improves code quality and design", is_correct: 1, question_id: 174 },
    { id: 348, answer: "Reduces the need for testing", is_correct: 0, question_id: 174 },
    { id: 349, answer: "True", is_correct: 1, question_id: 175 },
    { id: 350, answer: "False", is_correct: 0, question_id: 175 },
    { id: 351, answer: "Continuous delivery", is_correct: 1, question_id: 176 },
    { id: 352, answer: "Waterfall development", is_correct: 0, question_id: 176 },
    { id: 353, answer: "True", is_correct: 1, question_id: 177 },
    { id: 354, answer: "False", is_correct: 0, question_id: 177 },
    { id: 355, answer: "To shorten the systems development lifecycle", is_correct: 1, question_id: 178 },
    { id: 356, answer: "To increase the number of releases", is_correct: 0, question_id: 178 },
    { id: 357, answer: "Jenkins", is_correct: 1, question_id: 179 },
    { id: 358, answer: "Git", is_correct: 0, question_id: 179 },
    { id: 359, answer: "False", is_correct: 0, question_id: 180 },
    { id: 360, answer: "True", is_correct: 1, question_id: 180 },

    { id: 361, answer: "Containerization", is_correct: 1, question_id: 181 },
    { id: 362, answer: "Virtualization", is_correct: 0, question_id: 181 },
    { id: 363, answer: "True", is_correct: 1, question_id: 182 },
    { id: 364, answer: "False", is_correct: 0, question_id: 182 },
    { id: 365, answer: "docker build", is_correct: 1, question_id: 183 },
    { id: 366, answer: "docker run", is_correct: 0, question_id: 183 },
    { id: 367, answer: "A file containing instructions to build a Docker image", is_correct: 1, question_id: 184 },
    { id: 368, answer: "A file to run Docker containers", is_correct: 0, question_id: 184 },
    { id: 369, answer: "True", is_correct: 1, question_id: 185 },
    { id: 370, answer: "False", is_correct: 0, question_id: 185 },

    { id: 371, answer: "Orchestrating containers", is_correct: 1, question_id: 186 },
    { id: 372, answer: "Managing virtual machines", is_correct: 0, question_id: 186 },
    { id: 373, answer: "True", is_correct: 1, question_id: 187 },
    { id: 374, answer: "False", is_correct: 0, question_id: 187 },
    { id: 375, answer: "The Kubernetes scheduler", is_correct: 1, question_id: 188 },
    { id: 376, answer: "The API server", is_correct: 0, question_id: 188 },
    { id: 377, answer: "The smallest unit of deployment in Kubernetes", is_correct: 1, question_id: 189 },
    { id: 378, answer: "A virtual machine", is_correct: 0, question_id: 189 },
    { id: 379, answer: "False", is_correct: 1, question_id: 190 },
    { id: 380, answer: "True", is_correct: 0, question_id: 190 },
    { id: 381, answer: "Built-in enterprise features", is_correct: 1, question_id: 191 },
    { id: 382, answer: "Less complexity", is_correct: 0, question_id: 191 },
    { id: 383, answer: "True", is_correct: 1, question_id: 192 },
    { id: 384, answer: "False", is_correct: 0, question_id: 192 },
    { id: 385, answer: "Security, developer tools, and CI/CD pipelines", is_correct: 1, question_id: 193 },
    { id: 386, answer: "More container runtime options", is_correct: 0, question_id: 193 },
    { id: 387, answer: "Red Hat", is_correct: 1, question_id: 194 },
    { id: 388, answer: "Microsoft", is_correct: 0, question_id: 194 },
    { id: 389, answer: "False", is_correct: 1, question_id: 195 },
    { id: 390, answer: "True", is_correct: 0, question_id: 195 },
    { id: 391, answer: "Serverless computing", is_correct: 1, question_id: 196 },
    { id: 392, answer: "Virtual machine management", is_correct: 0, question_id: 196 },
    { id: 393, answer: "True", is_correct: 1, question_id: 197 },
    { id: 394, answer: "False", is_correct: 0, question_id: 197 },
    { id: 395, answer: "Amazon S3", is_correct: 1, question_id: 198 },
    { id: 396, answer: "Amazon RDS", is_correct: 0, question_id: 198 },
    { id: 397, answer: "Amazon RDS", is_correct: 1, question_id: 199 },
    { id: 398, answer: "Amazon EC2", is_correct: 0, question_id: 199 },
    { id: 399, answer: "True", is_correct: 1, question_id: 200 },
    { id: 400, answer: "False", is_correct: 0, question_id: 200 },
    { id: 401, answer: "Azure Virtual Machines", is_correct: 1, question_id: 201 },
    { id: 402, answer: "Azure Functions", is_correct: 0, question_id: 201 },
    { id: 403, answer: "True", is_correct: 1, question_id: 202 },
    { id: 404, answer: "False", is_correct: 0, question_id: 202 },
    { id: 405, answer: "Azure Blob Storage", is_correct: 1, question_id: 203 },
    { id: 406, answer: "Azure App Services", is_correct: 0, question_id: 203 },
    { id: 407, answer: "Azure SQL Database", is_correct: 1, question_id: 204 },
    { id: 408, answer: "Azure Data Lake", is_correct: 0, question_id: 204 },
    { id: 409, answer: "True", is_correct: 1, question_id: 205 },
    { id: 410, answer: "False", is_correct: 0, question_id: 205 },

    { id: 411, answer: "Google Cloud Storage", is_correct: 1, question_id: 206 },
    { id: 412, answer: "Google Cloud SQL", is_correct: 0, question_id: 206 },
    { id: 413, answer: "True", is_correct: 1, question_id: 207 },
    { id: 414, answer: "False", is_correct: 0, question_id: 207 },
    { id: 415, answer: "Google AI Platform", is_correct: 1, question_id: 208 },
    { id: 416, answer: "Google BigQuery", is_correct: 0, question_id: 208 },
    { id: 417, answer: "Google Compute Engine", is_correct: 1, question_id: 209 },
    { id: 418, answer: "Google Cloud Run", is_correct: 0, question_id: 209 },
    { id: 419, answer: "True", is_correct: 1, question_id: 210 },
    { id: 420, answer: "False", is_correct: 0, question_id: 210 },

    { id: 421, answer: "Infrastructure as Code", is_correct: 1, question_id: 211 },
    { id: 422, answer: "Application deployment", is_correct: 0, question_id: 211 },
    { id: 423, answer: "False", is_correct: 0, question_id: 212 },
    { id: 424, answer: "True", is_correct: 1, question_id: 212 },
    { id: 425, answer: "HCL (HashiCorp Configuration Language)", is_correct: 1, question_id: 213 },
    { id: 426, answer: "YAML", is_correct: 0, question_id: 213 },
    { id: 427, answer: "It applies the desired infrastructure state", is_correct: 1, question_id: 214 },
    { id: 428, answer: "It destroys the infrastructure", is_correct: 0, question_id: 214 },
    { id: 429, answer: "True", is_correct: 1, question_id: 215 },
    { id: 430, answer: "False", is_correct: 0, question_id: 215 },
    { id: 431, answer: "Configuration management and automation", is_correct: 1, question_id: 216 },
    { id: 432, answer: "Container orchestration", is_correct: 0, question_id: 216 },
    { id: 433, answer: "True", is_correct: 1, question_id: 217 },
    { id: 434, answer: "False", is_correct: 0, question_id: 217 },
    { id: 435, answer: "YAML", is_correct: 1, question_id: 218 },
    { id: 436, answer: "JSON", is_correct: 0, question_id: 218 },
    { id: 437, answer: "It defines the tasks for managing configurations", is_correct: 1, question_id: 219 },
    { id: 438, answer: "It defines container images", is_correct: 0, question_id: 219 },
    { id: 439, answer: "True", is_correct: 1, question_id: 220 },
    { id: 440, answer: "False", is_correct: 0, question_id: 220 },
    { id: 441, answer: "Testing individual units of code", is_correct: 1, question_id: 221 },
    { id: 442, answer: "Testing the entire application", is_correct: 0, question_id: 221 },
    { id: 443, answer: "True", is_correct: 1, question_id: 222 },
    { id: 444, answer: "False", is_correct: 0, question_id: 222 },
    { id: 445, answer: "Jest", is_correct: 1, question_id: 223 },
    { id: 446, answer: "Selenium", is_correct: 0, question_id: 223 },
    { id: 447, answer: "To validate that a single function works as expected", is_correct: 1, question_id: 224 },
    { id: 448, answer: "To validate the performance of the entire system", is_correct: 0, question_id: 224 },
    { id: 449, answer: "True", is_correct: 1, question_id: 225 },
    { id: 450, answer: "False", is_correct: 0, question_id: 225 },
    { id: 451, answer: "To test the interaction between integrated components", is_correct: 1, question_id: 226 },
    { id: 452, answer: "To test individual units of code", is_correct: 0, question_id: 226 },
    { id: 453, answer: "True", is_correct: 1, question_id: 227 },
    { id: 454, answer: "False", is_correct: 0, question_id: 227 },
    { id: 455, answer: "Big Bang testing", is_correct: 1, question_id: 228 },
    { id: 456, answer: "Unit testing", is_correct: 0, question_id: 228 },
    { id: 457, answer: "Unit testing", is_correct: 1, question_id: 229 },
    { id: 458, answer: "System testing", is_correct: 0, question_id: 229 },
    { id: 459, answer: "True", is_correct: 1, question_id: 230 },
    { id: 460, answer: "False", is_correct: 0, question_id: 230 },
    { id: 461, answer: "Testing the complete functionality of an application", is_correct: 1, question_id: 231 },
    { id: 462, answer: "Testing individual units", is_correct: 0, question_id: 231 },
    { id: 463, answer: "True", is_correct: 1, question_id: 232 },
    { id: 464, answer: "False", is_correct: 0, question_id: 232 },
    { id: 465, answer: "Cypress", is_correct: 1, question_id: 233 },
    { id: 466, answer: "JUnit", is_correct: 0, question_id: 233 },
    { id: 467, answer: "Ensures the flow works as expected", is_correct: 1, question_id: 234 },
    { id: 468, answer: "Tests individual components", is_correct: 0, question_id: 234 },
    { id: 469, answer: "False", is_correct: 1, question_id: 235 },
    { id: 470, answer: "True", is_correct: 0, question_id: 235 },
    { id: 471, answer: "Automating web browsers", is_correct: 1, question_id: 236 },
    { id: 472, answer: "Testing mobile apps", is_correct: 0, question_id: 236 },
    { id: 473, answer: "True", is_correct: 1, question_id: 237 },
    { id: 474, answer: "False", is_correct: 0, question_id: 237 },
    { id: 475, answer: "Java, Python, C#", is_correct: 1, question_id: 238 },
    { id: 476, answer: "Ruby, Kotlin", is_correct: 0, question_id: 238 },
    { id: 477, answer: "Selenium WebDriver", is_correct: 1, question_id: 239 },
    { id: 478, answer: "Mocha", is_correct: 0, question_id: 239 },
    { id: 479, answer: "False", is_correct: 1, question_id: 240 },
    { id: 480, answer: "True", is_correct: 0, question_id: 240 },
    { id: 481, answer: "Unit testing in JavaScript", is_correct: 0, question_id: 241 },
    { id: 482, answer: "Testing in JavaScript", is_correct: 1, question_id: 241 },
    { id: 483, answer: "True", is_correct: 1, question_id: 242 },
    { id: 484, answer: "False", is_correct: 0, question_id: 242 },
    { id: 485, answer: "React Testing Library", is_correct: 1, question_id: 243 },
    { id: 486, answer: "Mocha", is_correct: 0, question_id: 243 },
    { id: 487, answer: "To create consistent snapshots of component output", is_correct: 1, question_id: 244 },
    { id: 488, answer: "To manage state", is_correct: 0, question_id: 244 },
    { id: 489, answer: "True", is_correct: 1, question_id: 245 },
    { id: 490, answer: "False", is_correct: 0, question_id: 245 },
    { id: 491, answer: "Testing Node.js applications", is_correct: 1, question_id: 246 },
    { id: 492, answer: "Testing Python applications", is_correct: 0, question_id: 246 },
    { id: 493, answer: "True", is_correct: 1, question_id: 247 },
    { id: 494, answer: "False", is_correct: 0, question_id: 247 },
    { id: 495, answer: "Chai", is_correct: 1, question_id: 248 },
    { id: 496, answer: "Jasmine", is_correct: 0, question_id: 248 },
    { id: 497, answer: "Mocha allows asynchronous testing", is_correct: 1, question_id: 249 },
    { id: 498, answer: "Mocha is used for synchronous testing only", is_correct: 0, question_id: 249 },
    { id: 499, answer: "True", is_correct: 1, question_id: 250 },
    { id: 500, answer: "False", is_correct: 0, question_id: 250 },
    { id: 501, answer: "Representational State Transfer API", is_correct: 1, question_id: 251 },
    { id: 502, answer: "Request State Transfer API", is_correct: 0, question_id: 251 },
    { id: 503, answer: "True", is_correct: 1, question_id: 252 },
    { id: 504, answer: "False", is_correct: 0, question_id: 252 },
    { id: 505, answer: "JSON", is_correct: 1, question_id: 253 },
    { id: 506, answer: "YAML", is_correct: 0, question_id: 253 },
    { id: 507, answer: "The server does not store any client information between requests", is_correct: 1, question_id: 254 },
    { id: 508, answer: "The server stores session information for each client", is_correct: 0, question_id: 254 },
    { id: 509, answer: "False", is_correct: 1, question_id: 255 },
    { id: 510, answer: "True", is_correct: 0, question_id: 255 },
    { id: 511, answer: "Query language for APIs", is_correct: 1, question_id: 256 },
    { id: 512, answer: "Database language", is_correct: 0, question_id: 256 },
    { id: 513, answer: "True", is_correct: 1, question_id: 257 },
    { id: 514, answer: "False", is_correct: 0, question_id: 257 },
    { id: 515, answer: "Fewer requests to the server", is_correct: 1, question_id: 258 },
    { id: 516, answer: "Automatic data formatting", is_correct: 0, question_id: 258 },
    { id: 517, answer: "GraphQL schema defines types, queries, and mutations", is_correct: 1, question_id: 259 },
    { id: 518, answer: "GraphQL schema stores data", is_correct: 0, question_id: 259 },
    { id: 519, answer: "False", is_correct: 1, question_id: 260 },
    { id: 520, answer: "True", is_correct: 0, question_id: 260 },
    { id: 521, answer: "Simple Object Access Protocol", is_correct: 1, question_id: 261 },
    { id: 522, answer: "Secure Online Application Protocol", is_correct: 0, question_id: 261 },
    { id: 523, answer: "False", is_correct: 1, question_id: 262 },
    { id: 524, answer: "True", is_correct: 0, question_id: 262 },
    { id: 525, answer: "WSDL (Web Services Description Language)", is_correct: 1, question_id: 263 },
    { id: 526, answer: "HTML", is_correct: 0, question_id: 263 },
    { id: 527, answer: "SOAP is a protocol, REST is an architectural style", is_correct: 1, question_id: 264 },
    { id: 528, answer: "Both are protocols", is_correct: 0, question_id: 264 },
    { id: 529, answer: "True", is_correct: 1, question_id: 265 },
    { id: 530, answer: "False", is_correct: 0, question_id: 265 },
    { id: 531, answer: "Remote Procedure Call", is_correct: 1, question_id: 266 },
    { id: 532, answer: "Graphical Remote Procedure", is_correct: 0, question_id: 266 },
    { id: 533, answer: "True", is_correct: 1, question_id: 267 },
    { id: 534, answer: "False", is_correct: 0, question_id: 267 },
    { id: 535, answer: "Protocol Buffers (protobuf)", is_correct: 1, question_id: 268 },
    { id: 536, answer: "JSON", is_correct: 0, question_id: 268 },
    { id: 537, answer: "More efficient communication using HTTP/2", is_correct: 1, question_id: 269 },
    { id: 538, answer: "Better error handling", is_correct: 0, question_id: 269 },
    { id: 539, answer: "True", is_correct: 1, question_id: 270 },
    { id: 540, answer: "False", is_correct: 0, question_id: 270 },
    { id: 541, answer: "Full-duplex communication over a single TCP connection", is_correct: 1, question_id: 271 },
    { id: 542, answer: "Synchronous communication over multiple TCP connections", is_correct: 0, question_id: 271 },
    { id: 543, answer: "True", is_correct: 1, question_id: 272 },
    { id: 544, answer: "False", is_correct: 0, question_id: 272 },
    { id: 545, answer: "Real-time chat applications", is_correct: 1, question_id: 273 },
    { id: 546, answer: "Database management", is_correct: 0, question_id: 273 },
    { id: 547, answer: "WebSockets maintain an open connection", is_correct: 1, question_id: 274 },
    { id: 548, answer: "WebSockets close the connection after every message", is_correct: 0, question_id: 274 },
    { id: 549, answer: "True", is_correct: 1, question_id: 275 },
    { id: 550, answer: "False", is_correct: 0, question_id: 275 },
    { id: 551, answer: "Authorization and resource access delegation", is_correct: 1, question_id: 276 },
    { id: 552, answer: "Authentication of users", is_correct: 0, question_id: 276 },
    { id: 553, answer: "True", is_correct: 0, question_id: 277 },
    { id: 554, answer: "False", is_correct: 1, question_id: 277 },
    { id: 555, answer: "OAuth 2.0", is_correct: 1, question_id: 278 },
    { id: 556, answer: "OAuth 1.0", is_correct: 0, question_id: 278 },
    { id: 557, answer: "It grants access to protected resources", is_correct: 1, question_id: 279 },
    { id: 558, answer: "It logs users into the application", is_correct: 0, question_id: 279 },
    { id: 559, answer: "False", is_correct: 1, question_id: 280 },
    { id: 560, answer: "True", is_correct: 0, question_id: 280 },
    { id: 561, answer: "An architecture where an application is composed of small, independent services", is_correct: 1, question_id: 281 },
    { id: 562, answer: "An architecture where an application is a single, unified codebase", is_correct: 0, question_id: 281 },
    { id: 563, answer: "True", is_correct: 1, question_id: 282 },
    { id: 564, answer: "False", is_correct: 0, question_id: 282 },
    { id: 565, answer: "HTTP/REST", is_correct: 1, question_id: 283 },
    { id: 566, answer: "FTP", is_correct: 0, question_id: 283 },
    { id: 567, answer: "Easier scaling and independent deployment", is_correct: 1, question_id: 284 },
    { id: 568, answer: "Single database management", is_correct: 0, question_id: 284 },
    { id: 569, answer: "False", is_correct: 1, question_id: 285 },
    { id: 570, answer: "True", is_correct: 0, question_id: 285 },
    { id: 571, answer: "A unified codebase for all components", is_correct: 0, question_id: 286 },
    { id: 572, answer: "A single, tightly coupled application where all modules are integrated", is_correct: 1, question_id: 286 },
    { id: 573, answer: "True", is_correct: 1, question_id: 287 },
    { id: 574, answer: "False", is_correct: 0, question_id: 287 },
    { id: 575, answer: "Difficulty in scaling individual components", is_correct: 1, question_id: 288 },
    { id: 576, answer: "Modular design", is_correct: 0, question_id: 288 },
    { id: 577, answer: "Ease of deployment and testing", is_correct: 1, question_id: 289 },
    { id: 578, answer: "Difficulty in maintenance", is_correct: 0, question_id: 289 },
    { id: 579, answer: "True", is_correct: 1, question_id: 290 },
    { id: 580, answer: "False", is_correct: 0, question_id: 290 },
    { id: 581, answer: "An architecture where components react to events", is_correct: 1, question_id: 291 },
    { id: 582, answer: "An architecture where components communicate synchronously", is_correct: 0, question_id: 291 },
    { id: 583, answer: "True", is_correct: 1, question_id: 292 },
    { id: 584, answer: "False", is_correct: 0, question_id: 292 },
    { id: 585, answer: "Apache Kafka", is_correct: 1, question_id: 293 },
    { id: 586, answer: "SMTP", is_correct: 0, question_id: 293 },
    { id: 587, answer: "Decoupling of services and improved responsiveness", is_correct: 1, question_id: 294 },
    { id: 588, answer: "Increased complexity and latency", is_correct: 0, question_id: 294 },
    { id: 589, answer: "False", is_correct: 1, question_id: 295 },
    { id: 590, answer: "True", is_correct: 0, question_id: 295 },
    { id: 591, answer: "An architecture where services communicate over a network", is_correct: 1, question_id: 296 },
    { id: 592, answer: "An architecture where all components are integrated into a single application", is_correct: 0, question_id: 296 },
    { id: 593, answer: "False", is_correct: 0, question_id: 297 },
    { id: 594, answer: "True", is_correct: 1, question_id: 297 },
    { id: 595, answer: "SOAP", is_correct: 1, question_id: 298 },
    { id: 596, answer: "REST", is_correct: 0, question_id: 298 },
    { id: 597, answer: "Reusability and integration", is_correct: 1, question_id: 299 },
    { id: 598, answer: "Single point of failure", is_correct: 0, question_id: 299 },
    { id: 599, answer: "True", is_correct: 1, question_id: 300 },
    { id: 600, answer: "False", is_correct: 0, question_id: 300 },
    { id: 601, answer: "An architecture where server management is abstracted away", is_correct: 1, question_id: 301 },
    { id: 602, answer: "An architecture where servers are directly managed by the user", is_correct: 0, question_id: 301 },
    { id: 603, answer: "True", is_correct: 1, question_id: 302 },
    { id: 604, answer: "False", is_correct: 0, question_id: 302 },
    { id: 605, answer: "Function as a Service (FaaS)", is_correct: 1, question_id: 303 },
    { id: 606, answer: "Platform as a Service (PaaS)", is_correct: 0, question_id: 303 },
    { id: 607, answer: "Reduced operational overhead", is_correct: 1, question_id: 304 },
    { id: 608, answer: "Increased control over server configurations", is_correct: 0, question_id: 304 },
    { id: 609, answer: "False", is_correct: 1, question_id: 305 },
    { id: 610, answer: "True", is_correct: 0, question_id: 305 },
    { id: 611, answer: "A design pattern for separating concerns in applications", is_correct: 1, question_id: 306 },
    { id: 612, answer: "A method for securing application data", is_correct: 0, question_id: 306 },
    { id: 613, answer: "False", is_correct: 0, question_id: 307 },
    { id: 614, answer: "True", is_correct: 1, question_id: 307 },
    { id: 615, answer: "Manages user input and interactions", is_correct: 1, question_id: 308 },
    { id: 616, answer: "Manages the presentation of data", is_correct: 0, question_id: 308 },
    { id: 617, answer: "Separation of concerns and modularity", is_correct: 1, question_id: 309 },
    { id: 618, answer: "Complexity in data access", is_correct: 0, question_id: 309 },
    { id: 619, answer: "False", is_correct: 1, question_id: 310 },
    { id: 620, answer: "True", is_correct: 0, question_id: 310 },
    { id: 621, answer: "A tool for infrastructure automation and configuration management", is_correct: 1, question_id: 311 },
    { id: 622, answer: "A tool for real-time monitoring", is_correct: 0, question_id: 311 },
    { id: 623, answer: "True", is_correct: 1, question_id: 312 },
    { id: 624, answer: "False", is_correct: 0, question_id: 312 },
    { id: 625, answer: "Ruby", is_correct: 1, question_id: 313 },
    { id: 626, answer: "Python", is_correct: 0, question_id: 313 },
    { id: 627, answer: "Automated configuration and management", is_correct: 1, question_id: 314 },
    { id: 628, answer: "Manual server configuration", is_correct: 0, question_id: 314 },
    { id: 629, answer: "True", is_correct: 1, question_id: 315 },
    { id: 630, answer: "False", is_correct: 0, question_id: 315 },
    { id: 631, answer: "A tool for automating system administration tasks", is_correct: 1, question_id: 316 },
    { id: 632, answer: "A tool for managing network traffic", is_correct: 0, question_id: 316 },
    { id: 633, answer: "True", is_correct: 1, question_id: 317 },
    { id: 634, answer: "False", is_correct: 0, question_id: 317 },
    { id: 635, answer: "Ruby", is_correct: 1, question_id: 318 },
    { id: 636, answer: "Bash", is_correct: 0, question_id: 318 },
    { id: 637, answer: "Infrastructure automation", is_correct: 1, question_id: 319 },
    { id: 638, answer: "Manual configuration", is_correct: 0, question_id: 319 },
    { id: 639, answer: "True", is_correct: 1, question_id: 320 },
    { id: 640, answer: "False", is_correct: 0, question_id: 320 },
    { id: 641, answer: "A task automation framework", is_correct: 1, question_id: 321 },
    { id: 642, answer: "A graphical user interface tool", is_correct: 0, question_id: 321 },
    { id: 643, answer: "False", is_correct: 0, question_id: 322 },
    { id: 644, answer: "True", is_correct: 1, question_id: 322 },
    { id: 645, answer: "Cmdlet", is_correct: 1, question_id: 323 },
    { id: 646, answer: "Service", is_correct: 0, question_id: 323 },
    { id: 647, answer: "Integration with other Microsoft products", is_correct: 1, question_id: 324 },
    { id: 648, answer: "Limited scripting capabilities", is_correct: 0, question_id: 324 },
    { id: 649, answer: "True", is_correct: 1, question_id: 325 },
    { id: 650, answer: "False", is_correct: 0, question_id: 325 }
    














]
