export default [
  
    { id: 1, question: "What is JavaScript primarily used for?", skill_id: 1 },
    { id: 2, question: "Which of the following is a JavaScript data type?", skill_id: 1 },
    { id: 3, question: "Which method is used to parse a string to an integer in JavaScript?", skill_id: 1 },
    { id: 4, question: "True or False: JavaScript is a case-sensitive language.", skill_id: 1 },
    { id: 5, question: "Which keyword is used to declare a variable in JavaScript?", skill_id: 1 },
    { id: 6, question: "What is Python primarily known for?", skill_id: 2 },
    { id: 7, question: "Which keyword is used to define a function in Python?", skill_id: 2 },
    { id: 8, question: "True or False: Python is an interpreted language.", skill_id: 2 },
    { id: 9, question: "Which of the following is a Python data structure?", skill_id: 2 },
    { id: 10, question: "Which library is commonly used for data analysis in Python?", skill_id: 2 },
    { id: 11, question: "Which keyword is used to define a class in Java?", skill_id: 3 },
    { id: 12, question: "What does JVM stand for?", skill_id: 3 },
    { id: 13, question: "True or False: Java supports multiple inheritance.", skill_id: 3 },
    { id: 14, question: "Which method is used to start the execution of a Java program?", skill_id: 3 },
    { id: 15, question: "Which data type is used to create an object in Java?", skill_id: 3 },
    { id: 16, question: "What does the '++' in C++ signify?", skill_id: 4 },
    { id: 17, question: "Which of the following is not a feature of C++?", skill_id: 4 },
    { id: 18, question: "True or False: C++ supports object-oriented programming.", skill_id: 4 },
    { id: 19, question: "Which operator is used to access a class member in C++?", skill_id: 4 },
    { id: 20, question: "Which of the following is a C++ loop structure?", skill_id: 4 },
    { id: 21, question: "Which keyword is used to declare a method in C#?", skill_id: 5 },
    { id: 22, question: "True or False: C# is a statically typed language.", skill_id: 5 },
    { id: 23, question: "Which of the following is a C# data type?", skill_id: 5 },
    { id: 24, question: "Which keyword is used to declare a constant in C#?", skill_id: 5 },
    { id: 25, question: "Which framework is primarily used with C# for web development?", skill_id: 5 },
    { id: 26, question: "Which keyword is used to define a method in Ruby?", skill_id: 6 },
    { id: 27, question: "True or False: Ruby is an object-oriented language.", skill_id: 6 },
    { id: 28, question: "Which symbol is used to denote an instance variable in Ruby?", skill_id: 6 },
    { id: 29, question: "Which of the following is a Ruby web framework?", skill_id: 6 },
    { id: 30, question: "What is the name of Ruby's package manager?", skill_id: 6 },
    { id: 31, question: "Which SQL statement is used to retrieve data from a database?", skill_id: 7 },
    { id: 32, question: "True or False: SQL is case-sensitive.", skill_id: 7 },
    { id: 33, question: "Which SQL command is used to update existing records?", skill_id: 7 },
    { id: 34, question: "What does SQL stand for?", skill_id: 7 },
    { id: 35, question: "Which clause is used to filter records in SQL?", skill_id: 7 },
    { id: 36, question: "MongoDB is an example of which type of database?", skill_id: 8 },
    { id: 37, question: "What does BSON stand for?", skill_id: 8 },
    { id: 38, question: "True or False: MongoDB supports ACID transactions.", skill_id: 8 },
    { id: 39, question: "Which command is used to insert a document in MongoDB?", skill_id: 8 },
    { id: 40, question: "What is the default port number for MongoDB?", skill_id: 8 },
    { id: 41, question: "Which SQL standard does PostgreSQL closely adhere to?", skill_id: 9 },
    { id: 42, question: "True or False: PostgreSQL supports JSON data types.", skill_id: 9 },
    { id: 43, question: "Which command is used to create a database in PostgreSQL?", skill_id: 9 },
    { id: 44, question: "Which type of indexing is supported by PostgreSQL?", skill_id: 9 },
    { id: 45, question: "Which language is PostgreSQL written in?", skill_id: 9 },
    { id: 46, question: "Which company developed MySQL?", skill_id: 10 },
    { id: 47, question: "Which storage engine is the default in MySQL?", skill_id: 10 },
    { id: 48, question: "True or False: MySQL is open source.", skill_id: 10 },
    { id: 49, question: "Which command is used to view databases in MySQL?", skill_id: 10 },
    { id: 50, question: "What is the maximum size of a VARCHAR field in MySQL?", skill_id: 10 },
    { id: 51, question: "What type of data store is Redis?", skill_id: 11 },
    { id: 52, question: "What does Redis stand for?", skill_id: 11 },
    { id: 53, question: "True or False: Redis supports transactions.", skill_id: 11 },
    { id: 54, question: "Which command is used to set a key-value pair in Redis?", skill_id: 11 },
    { id: 55, question: "Which data structure is NOT supported by Redis?", skill_id: 11 },
    { id: 56, question: "True or False: SQLite is serverless.", skill_id: 12 },
    { id: 57, question: "Which file extension is used by SQLite databases?", skill_id: 12 },
    { id: 58, question: "What is the maximum size of an SQLite database?", skill_id: 12 },
    { id: 59, question: "Which command is used to open an SQLite database?", skill_id: 12 },
    { id: 60, question: "Which function is used to calculate the total number of rows in SQLite?", skill_id: 12 },
    { id: 61, question: "Which company developed React.js?", skill_id: 13 },
    { id: 62, question: "What is the primary purpose of React.js?", skill_id: 13 },
    { id: 63, question: "True or False: React is a backend framework.", skill_id: 13 },
    { id: 64, question: "Which keyword is used to create a class-based component in React?", skill_id: 13 },
    { id: 65, question: "What does JSX stand for?", skill_id: 13 },
    { id: 66, question: "Which of the following is a key feature of Vue.js?", skill_id: 14 },
    { id: 67, question: "What is the command to create a new Vue.js project using Vue CLI?", skill_id: 14 },
    { id: 68, question: "True or False: Vue.js is a full-fledged framework like Angular.", skill_id: 14 },
    { id: 69, question: "What is the template syntax used in Vue.js?", skill_id: 14 },
    { id: 70, question: "Who developed Vue.js?", skill_id: 14 },
    { id: 71, question: "Which company developed Angular?", skill_id: 15 },
    { id: 72, question: "What programming language is primarily used in Angular?", skill_id: 15 },
    { id: 73, question: "True or False: Angular is a frontend framework.", skill_id: 15 },
    { id: 74, question: "Which directive is used to loop over a collection in Angular?", skill_id: 15 },
    { id: 75, question: "What is the primary building block of Angular applications?", skill_id: 15 },
    { id: 76, question: "What is the key difference between Svelte and other frontend frameworks?", skill_id: 16 },
    { id: 77, question: "Which command is used to create a new Svelte project?", skill_id: 16 },
    { id: 78, question: "True or False: Svelte compiles components at runtime.", skill_id: 16 },
    { id: 79, question: "Who created Svelte?", skill_id: 16 },
    { id: 80, question: "Which directive is used for looping in Svelte?", skill_id: 16 },
    { id: 81, question: "Which company developed Bootstrap?", skill_id: 17 },
    { id: 82, question: "What is the primary purpose of Bootstrap?", skill_id: 17 },
    { id: 83, question: "True or False: Bootstrap is a CSS framework.", skill_id: 17 },
    { id: 84, question: "Which class is used to create a grid system in Bootstrap?", skill_id: 17 },
    { id: 85, question: "Which preprocessor does Bootstrap support?", skill_id: 17 },
    { id: 86, question: "What is the main advantage of using jQuery?", skill_id: 18 },
    { id: 87, question: "Which symbol is used to access jQuery?", skill_id: 18 },
    { id: 88, question: "True or False: jQuery simplifies HTML DOM tree traversal and manipulation.", skill_id: 18 },
    { id: 89, question: "Which function is used to hide an element in jQuery?", skill_id: 18 },
    { id: 90, question: "Which jQuery method is used to perform asynchronous HTTP requests?", skill_id: 18 },
    { id: 91, question: "What is Node.js primarily used for?", skill_id: 19 },
    { id: 92, question: "Which of the following is a core module in Node.js?", skill_id: 19 },
    { id: 93, question: "True or False: Node.js uses a single-threaded model.", skill_id: 19 },
    { id: 94, question: "Which command is used to install Node.js packages?", skill_id: 19 },
    { id: 95, question: "What is the default package manager for Node.js?", skill_id: 19 },
    { id: 96, question: "What type of framework is Django?", skill_id: 20 },
    { id: 97, question: "What programming language does Django use?", skill_id: 20 },
    { id: 98, question: "True or False: Django follows the Model-View-Controller (MVC) pattern.", skill_id: 20 },
    { id: 99, question: "Which command is used to start a new Django project?", skill_id: 20 },
    { id: 100, question: "What is the purpose of Django's ORM?", skill_id: 20 },
    { id: 101, question: "What is the primary purpose of Spring Boot?", skill_id: 21 },
    { id: 102, question: "Which file format is commonly used for Spring Boot configuration?", skill_id: 21 },
    { id: 103, question: "True or False: Spring Boot simplifies Spring application setup.", skill_id: 21 },
    { id: 104, question: "Which annotation is used to denote a Spring Boot application?", skill_id: 21 },
    { id: 105, question: "What is the default embedded server in Spring Boot?", skill_id: 21 },
    { id: 106, question: "What is Express.js primarily used for?", skill_id: 22 },
    { id: 107, question: "Which method is used to handle GET requests in Express.js?", skill_id: 22 },
    { id: 108, question: "True or False: Express.js is a framework for Node.js.", skill_id: 22 },
    { id: 109, question: "Which object is passed as a second argument to the callback function of a route in Express.js?", skill_id: 22 },
    { id: 110, question: "How do you start an Express.js application?", skill_id: 22 },
    { id: 111, question: "What is the primary design philosophy of Ruby on Rails?", skill_id: 23 },
    { id: 112, question: "Which language is Ruby on Rails written in?", skill_id: 23 },
    { id: 113, question: "True or False: Ruby on Rails follows the Model-View-Controller architecture.", skill_id: 23 },
    { id: 114, question: "Which command is used to create a new Ruby on Rails project?", skill_id: 23 },
    { id: 115, question: "What is ActiveRecord in Ruby on Rails?", skill_id: 23 },
    { id: 116, question: "What type of framework is Flask?", skill_id: 24 },
    { id: 117, question: "Which programming language is Flask based on?", skill_id: 24 },
    { id: 118, question: "True or False: Flask is a microframework.", skill_id: 24 },
    { id: 119, question: "Which command is used to start a Flask application?", skill_id: 24 },
    { id: 120, question: "What does Flask use for templating?", skill_id: 24 },
    { id: 121, question: "What is Git primarily used for?", skill_id: 25 },
    { id: 122, question: "Which command is used to check the current status of a Git repository?", skill_id: 25 },
    { id: 123, question: "True or False: Git is a distributed version control system.", skill_id: 25 },
    { id: 124, question: "Which command is used to clone a repository in Git?", skill_id: 25 },
    { id: 125, question: "Which file is used to ignore specific files in a Git repository?", skill_id: 25 },
    { id: 126, question: "What is GitHub primarily used for?", skill_id: 26 },
    { id: 127, question: "Which file is used to define a GitHub Action workflow?", skill_id: 26 },
    { id: 128, question: "True or False: GitHub provides both public and private repositories.", skill_id: 26 },
    { id: 129, question: "Which GitHub feature allows users to track bugs and feature requests?", skill_id: 26 },
    { id: 130, question: "Which command is used to push local commits to a GitHub repository?", skill_id: 26 },
    { id: 131, question: "What is GitLab's primary function?", skill_id: 27 },
    { id: 132, question: "Which GitLab feature is used for Continuous Integration/Continuous Deployment (CI/CD)?", skill_id: 27 },
    { id: 133, question: "True or False: GitLab is only available as a cloud-based service.", skill_id: 27 },
    { id: 134, question: "Which command is used to clone a GitLab repository?", skill_id: 27 },
    { id: 135, question: "What is the purpose of GitLab Runners?", skill_id: 27 },
    { id: 136, question: "What is Bitbucket primarily used for?", skill_id: 28 },
    { id: 137, question: "Which version control system does Bitbucket support in addition to Git?", skill_id: 28 },
    { id: 138, question: "True or False: Bitbucket is part of the Atlassian suite.", skill_id: 28 },
    { id: 139, question: "What feature does Bitbucket Pipelines provide?", skill_id: 28 },
    { id: 140, question: "Which command is used to fetch updates from a Bitbucket repository?", skill_id: 28 },
    { id: 141, question: "What is SVN primarily used for?", skill_id: 29 },
    { id: 142, question: "What does SVN stand for?", skill_id: 29 },
    { id: 143, question: "True or False: SVN is a distributed version control system.", skill_id: 29 },
    { id: 144, question: "Which command is used to check out an SVN repository?", skill_id: 29 },
    { id: 145, question: "How are revisions tracked in SVN?", skill_id: 29 },
    { id: 146, question: "What is Mercurial primarily used for?", skill_id: 30 },
    { id: 147, question: "Which command is used to clone a Mercurial repository?", skill_id: 30 },
    { id: 148, question: "True or False: Mercurial is a distributed version control system.", skill_id: 30 },
    { id: 149, question: "What file is used to configure ignore rules in Mercurial?", skill_id: 30 },
    { id: 150, question: "Which Mercurial command is used to commit changes?", skill_id: 30 },
    { id: 151, question: "What is the main focus of Agile methodologies?", skill_id: 31 },
    { id: 152, question: "True or False: Agile methodologies prioritize responding to change over following a strict plan.", skill_id: 31 },
    { id: 153, question: "Which of the following is a key Agile principle?", skill_id: 31 },
    { id: 154, question: "What does Agile recommend for delivering software?", skill_id: 31 },
    { id: 155, question: "True or False: Agile methodologies emphasize collaboration with the customer throughout the project.", skill_id: 31 },
    { id: 156, question: "In Scrum, what is the role of the Product Owner?", skill_id: 32 },
    { id: 157, question: "True or False: A sprint is a time-boxed iteration in Scrum.", skill_id: 32 },
    { id: 158, question: "What is a daily stand-up in Scrum?", skill_id: 32 },
    { id: 159, question: "Which artifact in Scrum holds the list of work to be done?", skill_id: 32 },
    { id: 160, question: "What is the role of the Scrum Master?", skill_id: 32 },
    { id: 161, question: "What is the primary purpose of a Kanban board?", skill_id: 33 },
    { id: 162, question: "True or False: Kanban limits work in progress (WIP) to improve flow.", skill_id: 33 },
    { id: 163, question: "Which principle is a key aspect of Kanban?", skill_id: 33 },
    { id: 164, question: "What is the main difference between Scrum and Kanban?", skill_id: 33 },
    { id: 165, question: "True or False: Kanban requires time-boxed iterations.", skill_id: 33 },
    { id: 166, question: "What is the goal of Continuous Integration (CI)?", skill_id: 34 },
    { id: 167, question: "True or False: In CI, code is integrated into a shared repository frequently.", skill_id: 34 },
    { id: 168, question: "Which tool is commonly used for Continuous Integration?", skill_id: 34 },
    { id: 169, question: "How does CI help in software development?", skill_id: 34 },
    { id: 170, question: "True or False: Continuous Integration requires automated testing.", skill_id: 34 },
    { id: 171, question: "What is the core principle of Test-Driven Development (TDD)?", skill_id: 35 },
    { id: 172, question: "True or False: In TDD, tests are written before code.", skill_id: 35 },
    { id: 173, question: "Which phase comes first in the TDD cycle?", skill_id: 35 },
    { id: 174, question: "What benefit does TDD provide?", skill_id: 35 },
    { id: 175, question: "True or False: TDD helps to ensure that code meets its requirements.", skill_id: 35 },
    { id: 176, question: "Which of the following is a core DevOps practice?", skill_id: 36 },
    { id: 177, question: "True or False: DevOps aims to reduce the time between development and deployment.", skill_id: 36 },
    { id: 178, question: "What is the primary goal of DevOps?", skill_id: 36 },
    { id: 179, question: "Which tool is commonly used in DevOps for continuous integration?", skill_id: 36 },
    { id: 180, question: "True or False: DevOps eliminates the need for separate development and operations teams.", skill_id: 36 },
    { id: 181, question: "What is Docker primarily used for?", skill_id: 37 },
    { id: 182, question: "True or False: Docker containers run directly on the host machine’s operating system.", skill_id: 37 },
    { id: 183, question: "Which command is used to build a Docker image?", skill_id: 37 },
    { id: 184, question: "What is a Dockerfile?", skill_id: 37 },
    { id: 185, question: "True or False: Docker containers are isolated from each other by default.", skill_id: 37 },
    { id: 186, question: "What is Kubernetes used for?", skill_id: 38 },
    { id: 187, question: "True or False: Kubernetes manages containerized applications across multiple hosts.", skill_id: 38 },
    { id: 188, question: "Which component in Kubernetes is responsible for scheduling pods?", skill_id: 38 },
    { id: 189, question: "What is a pod in Kubernetes?", skill_id: 38 },
    { id: 190, question: "True or False: A Kubernetes cluster can only run on one machine.", skill_id: 38 },
    { id: 191, question: "What is the main benefit of OpenShift over vanilla Kubernetes?", skill_id: 39 },
    { id: 192, question: "True or False: OpenShift is an enterprise Kubernetes platform.", skill_id: 39 },
    { id: 193, question: "What additional features does OpenShift provide compared to Kubernetes?", skill_id: 39 },
    { id: 194, question: "Which company develops OpenShift?", skill_id: 39 },
    { id: 195, question: "True or False: OpenShift requires Docker for its container engine.", skill_id: 39 },
    { id: 196, question: "What service does AWS Lambda provide?", skill_id: 40 },
    { id: 197, question: "True or False: AWS is a cloud computing platform.", skill_id: 40 },
    { id: 198, question: "Which AWS service is used for scalable object storage?", skill_id: 40 },
    { id: 199, question: "What is the primary database service provided by AWS?", skill_id: 40 },
    { id: 200, question: "True or False: AWS Elastic Beanstalk is a PaaS (Platform as a Service).", skill_id: 40 },
    { id: 201, question: "Which service is used for deploying virtual machines in Microsoft Azure?", skill_id: 41 },
    { id: 202, question: "True or False: Microsoft Azure provides a serverless computing service.", skill_id: 41 },
    { id: 203, question: "What is the primary storage service in Microsoft Azure?", skill_id: 41 },
    { id: 204, question: "Which tool in Microsoft Azure is used for managing databases?", skill_id: 41 },
    { id: 205, question: "True or False: Microsoft Azure supports both Windows and Linux virtual machines.", skill_id: 41 },
    { id: 206, question: "What is Google Cloud Platform's data storage service called?", skill_id: 42 },
    { id: 207, question: "True or False: Google Cloud offers Kubernetes as a managed service.", skill_id: 42 },
    { id: 208, question: "Which Google Cloud service is used for machine learning?", skill_id: 42 },
    { id: 209, question: "What is the primary compute service in Google Cloud?", skill_id: 42 },
    { id: 210, question: "True or False: Google Cloud Platform offers BigQuery as a data warehousing solution.", skill_id: 42 },
    { id: 211, question: "What is Terraform used for?", skill_id: 43 },
    { id: 212, question: "True or False: Terraform is a configuration management tool.", skill_id: 43 },
    { id: 213, question: "Which language is used to write Terraform configuration files?", skill_id: 43 },
    { id: 214, question: "What does 'Terraform apply' do?", skill_id: 43 },
    { id: 215, question: "True or False: Terraform can manage resources across multiple cloud providers.", skill_id: 43 },
    { id: 216, question: "What is the purpose of Ansible?", skill_id: 44 },
    { id: 217, question: "True or False: Ansible uses SSH to communicate with nodes.", skill_id: 44 },
    { id: 218, question: "Which language is used for writing Ansible playbooks?", skill_id: 44 },
    { id: 219, question: "What does an Ansible playbook define?", skill_id: 44 },
    { id: 220, question: "True or False: Ansible is agentless.", skill_id: 44 },
    { id: 221, question: "What is unit testing?", skill_id: 45 },
    { id: 222, question: "True or False: Unit tests are typically written by developers.", skill_id: 45 },
    { id: 223, question: "Which tool is commonly used for unit testing in JavaScript?", skill_id: 45 },
    { id: 224, question: "What is the purpose of a unit test?", skill_id: 45 },
    { id: 225, question: "True or False: Unit testing helps detect bugs early in the development process.", skill_id: 45 },
    { id: 226, question: "What is the purpose of integration testing?", skill_id: 46 },
    { id: 227, question: "True or False: Integration tests check the interaction between multiple components.", skill_id: 46 },
    { id: 228, question: "Which of the following is a type of integration testing?", skill_id: 46 },
    { id: 229, question: "Which phase comes before integration testing in a typical development process?", skill_id: 46 },
    { id: 230, question: "True or False: Integration testing is done after unit testing.", skill_id: 46 },
    { id: 231, question: "What is end-to-end testing?", skill_id: 47 },
    { id: 232, question: "True or False: End-to-end testing verifies the flow of an application from start to finish.", skill_id: 47 },
    { id: 233, question: "Which tool is commonly used for end-to-end testing?", skill_id: 47 },
    { id: 234, question: "What does end-to-end testing ensure?", skill_id: 47 },
    { id: 235, question: "True or False: End-to-end testing is the same as unit testing.", skill_id: 47 },
    { id: 236, question: "What is Selenium primarily used for?", skill_id: 48 },
    { id: 237, question: "True or False: Selenium is used for automating web browsers.", skill_id: 48 },
    { id: 238, question: "Which programming languages are supported by Selenium?", skill_id: 48 },
    { id: 239, question: "Which of the following is a component of Selenium?", skill_id: 48 },
    { id: 240, question: "True or False: Selenium can be used for mobile app testing.", skill_id: 48 },
    { id: 241, question: "What is Jest commonly used for?", skill_id: 49 },
    { id: 242, question: "True or False: Jest is a JavaScript testing framework.", skill_id: 49 },
    { id: 243, question: "Which library is commonly used alongside Jest for testing React applications?", skill_id: 49 },
    { id: 244, question: "What is the purpose of a Jest 'snapshot'?", skill_id: 49 },
    { id: 245, question: "True or False: Jest supports mocking functions and modules.", skill_id: 49 },
    { id: 246, question: "What type of testing is Mocha primarily used for?", skill_id: 50 },
    { id: 247, question: "True or False: Mocha is used for testing Node.js applications.", skill_id: 50 },
    { id: 248, question: "Which assertion library is commonly used with Mocha?", skill_id: 50 },
    { id: 249, question: "What is the main feature of Mocha?", skill_id: 50 },
    { id: 250, question: "True or False: Mocha runs tests serially, allowing for flexible reporting.", skill_id: 50 },
    { id: 251, question: "What does RESTful API stand for?", skill_id: 51 },
    { id: 252, question: "True or False: RESTful APIs use HTTP methods such as GET, POST, PUT, DELETE.", skill_id: 51 },
    { id: 253, question: "Which format is commonly used for data exchange in RESTful APIs?", skill_id: 51 },
    { id: 254, question: "What does the 'stateless' nature of RESTful APIs mean?", skill_id: 51 },
    { id: 255, question: "True or False: RESTful APIs must use JSON exclusively.", skill_id: 51 },
    { id: 256, question: "What is GraphQL used for?", skill_id: 52 },
    { id: 257, question: "True or False: GraphQL allows clients to specify the shape of the data they receive.", skill_id: 52 },
    { id: 258, question: "Which of the following is an advantage of GraphQL over REST?", skill_id: 52 },
    { id: 259, question: "What is a GraphQL schema?", skill_id: 52 },
    { id: 260, question: "True or False: GraphQL is stateless like REST.", skill_id: 52 },
    { id: 261, question: "What does SOAP stand for?", skill_id: 53 },
    { id: 262, question: "True or False: SOAP is a lightweight, stateless protocol.", skill_id: 53 },
    { id: 263, question: "Which language is typically used to define SOAP services?", skill_id: 53 },
    { id: 264, question: "What is one key difference between SOAP and REST?", skill_id: 53 },
    { id: 265, question: "True or False: SOAP services typically use XML for message formatting.", skill_id: 53 },
    { id: 266, question: "What is gRPC?", skill_id: 54 },
    { id: 267, question: "True or False: gRPC is based on HTTP/2.", skill_id: 54 },
    { id: 268, question: "Which language is used to define gRPC service interfaces?", skill_id: 54 },
    { id: 269, question: "What is an advantage of gRPC over REST?", skill_id: 54 },
    { id: 270, question: "True or False: gRPC supports multiple programming languages.", skill_id: 54 },
    { id: 271, question: "What is WebSockets primarily used for?", skill_id: 55 },
    { id: 272, question: "True or False: WebSockets provide a full-duplex communication channel over a single TCP connection.", skill_id: 55 },
    { id: 273, question: "Which type of applications often use WebSockets?", skill_id: 55 },
    { id: 274, question: "What is a key difference between WebSockets and HTTP?", skill_id: 55 },
    { id: 275, question: "True or False: WebSockets are stateless.", skill_id: 55 },
     { id: 276, question: "What is the primary use of OAuth?", skill_id: 56 },
     { id: 277, question: "True or False: OAuth is a single sign-on (SSO) protocol.", skill_id: 56 },
     { id: 278, question: "Which version of OAuth is most widely used?", skill_id: 56 },
     { id: 279, question: "What is an OAuth access token used for?", skill_id: 56 },
     { id: 280, question: "True or False: OAuth requires the user's password to be stored on the client application.", skill_id: 56 },
     { id: 281, question: "What is a microservice architecture?", skill_id: 57 },
     { id: 282, question: "True or False: Microservices are easier to scale than monolithic architectures.", skill_id: 57 },
     { id: 283, question: "Which protocol is commonly used for communication between microservices?", skill_id: 57 },
     { id: 284, question: "What is one advantage of microservices?", skill_id: 57 },
     { id: 285, question: "True or False: Microservices share a single database across all services.", skill_id: 57 },
     { id: 286, question: "What characterizes a monolithic architecture?", skill_id: 58 },
     { id: 287, question: "True or False: Monolithic applications are harder to deploy than microservices.", skill_id: 58 },
     { id: 288, question: "What is one disadvantage of a monolithic architecture?", skill_id: 58 },
     { id: 289, question: "What is a key benefit of a monolithic architecture?", skill_id: 58 },
     { id: 290, question: "True or False: In monolithic architectures, all components are tightly coupled.", skill_id: 58 },
     { id: 291, question: "What is an event-driven architecture?", skill_id: 59 },
     { id: 292, question: "True or False: In an event-driven architecture, components communicate via events.", skill_id: 59 },
     { id: 293, question: "What is a common messaging system used in event-driven architectures?", skill_id: 59 },
     { id: 294, question: "What is one advantage of using event-driven architecture?", skill_id: 59 },
     { id: 295, question: "True or False: Event-driven architectures have higher latency than request-response architectures.", skill_id: 59 },
     { id: 296, question: "What is the main principle behind Service-Oriented Architecture (SOA)?", skill_id: 60 },
     { id: 297, question: "True or False: SOA and microservices are the same.", skill_id: 60 },
     { id: 298, question: "Which protocol is commonly used in SOA?", skill_id: 60 },
     { id: 299, question: "What is one benefit of using SOA?", skill_id: 60 },
     { id: 300, question: "True or False: SOA allows for reusable services.", skill_id: 60 },
     { id: 301, question: "What is serverless architecture?", skill_id: 61 },
     { id: 302, question: "True or False: In serverless architecture, you don't need to manage servers.", skill_id: 61 },
     { id: 303, question: "Which service model is used in serverless architectures?", skill_id: 61 },
     { id: 304, question: "What is one advantage of using serverless architecture?", skill_id: 61 },
     { id: 305, question: "True or False: Serverless architectures are typically less scalable than traditional server-based ones.", skill_id: 61 },
     { id: 306, question: "What does MVC stand for?", skill_id: 62 },
     { id: 307, question: "True or False: In MVC, the Model is responsible for handling user input.", skill_id: 62 },
     { id: 308, question: "What is the role of the Controller in MVC?", skill_id: 62 },
     { id: 309, question: "What is the advantage of using MVC architecture?", skill_id: 62 },
     { id: 310, question: "True or False: The View in MVC architecture handles business logic.", skill_id: 62 },
     { id: 311, question: "What is Puppet used for?", skill_id: 64 },
     { id: 312, question: "True or False: Puppet is used for software deployment.", skill_id: 64 },
     { id: 313, question: "Which language is primarily used to write Puppet manifests?", skill_id: 64 },
     { id: 314, question: "What is one advantage of using Puppet for infrastructure automation?", skill_id: 64 },
     { id: 315, question: "True or False: Puppet uses a client-server architecture.", skill_id: 64 },
     { id: 316, question: "What is Chef primarily used for?", skill_id: 65 },
     { id: 317, question: "True or False: Chef is a tool for managing configurations.", skill_id: 65 },
     { id: 318, question: "Which language is primarily used to write Chef cookbooks?", skill_id: 65 },
     { id: 319, question: "What is one benefit of using Chef?", skill_id: 65 },
     { id: 320, question: "True or False: Chef operates in a declarative manner.", skill_id: 65 },
     { id: 321, question: "What is PowerShell?", skill_id: 67 },
     { id: 322, question: "True or False: PowerShell is exclusive to Windows systems.", skill_id: 67 },
     { id: 323, question: "What is a cmdlet in PowerShell?", skill_id: 67 },
     { id: 324, question: "What is one benefit of using PowerShell for scripting?", skill_id: 67 },
     { id: 325, question: "True or False: PowerShell supports pipeline commands.", skill_id: 67 }














]
