export default [
    {"id": 1, "question": "Which of the following is not a JavaScript data type?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 2, "question": "What is the correct syntax to declare a variable in JavaScript?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 3, "question": "Which function is used to parse a string to an integer in JavaScript?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 4, "question": "Which of the following is a JavaScript framework?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 5, "question": "True or False: JavaScript is a compiled language.", "skill_id": 1, "skill": "JavaScript"},
  {"id": 6, "question": "Which of the following is used to define a block of code in JavaScript?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 7, "question": "How do you create an array in JavaScript?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 8, "question": "Which method can be used to add a new element at the end of an array in JavaScript?", "skill_id": 1, "skill": "JavaScript"},
  {"id": 9, "question": "True or False: JavaScript supports both client-side and server-side development.", "skill_id": 1, "skill": "JavaScript"},
  {"id": 10, "question": "Which symbol is used for comments in JavaScript?", "skill_id": 1, "skill": "JavaScript"},

  {"id": 11, "question": "In Python, which keyword is used to define a function?", "skill_id": 2, "skill": "Python"},
  {"id": 12, "question": "What data type is the result of the expression: 5/2 in Python?", "skill_id": 2, "skill": "Python"},
  {"id": 13, "question": "Which of the following is a Python framework for web development?", "skill_id": 2, "skill": "Python"},
  {"id": 14, "question": "How do you create a list in Python?", "skill_id": 2, "skill": "Python"},
  {"id": 15, "question": "True or False: Python is a statically typed language.", "skill_id": 2, "skill": "Python"},
  {"id": 16, "question": "Which function is used to output text in Python?", "skill_id": 2, "skill": "Python"},
  {"id": 17, "question": "How do you create a dictionary in Python?", "skill_id": 2, "skill": "Python"},
  {"id": 18, "question": "Which keyword is used to handle exceptions in Python?", "skill_id": 2, "skill": "Python"},
  {"id": 19, "question": "True or False: Python supports object-oriented programming.", "skill_id": 2, "skill": "Python"},
  {"id": 20, "question": "What is the output of print(len('hello'))?", "skill_id": 2, "skill": "Python"},

  {"id": 21, "question": "True or False: Java is a statically typed language.", "skill_id": 3, "skill": "Java"},
  {"id": 22, "question": "Which of the following is not a Java primitive data type?", "skill_id": 3, "skill": "Java"},
  {"id": 23, "question": "Which of the following is a valid way to start the main method in Java?", "skill_id": 3, "skill": "Java"},
  {"id": 24, "question": "Which keyword is used to inherit a class in Java?", "skill_id": 3, "skill": "Java"},
  {"id": 25, "question": "True or False: Java supports multiple inheritance.", "skill_id": 3, "skill": "Java"},
  {"id": 26, "question": "Which class in Java can be used to handle file input/output?", "skill_id": 3, "skill": "Java"},
  {"id": 27, "question": "How do you create an array in Java?", "skill_id": 3, "skill": "Java"},
  {"id": 28, "question": "What is the output of 2 + 3 in Java?", "skill_id": 3, "skill": "Java"},
  {"id": 29, "question": "Which access modifier is used to make a class visible to all other classes?", "skill_id": 3, "skill": "Java"},
  {"id": 30, "question": "Which of the following is a package in Java?", "skill_id": 3, "skill": "Java"},

  {"id": 31, "question": "Which of the following operators is used for pointer access in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 32, "question": "Which function is used to allocate memory dynamically in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 33, "question": "True or False: C++ is an object-oriented programming language.", "skill_id": 4, "skill": "C++"},
  {"id": 34, "question": "Which keyword is used to define a constant variable in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 35, "question": "What is the default return type of the main function in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 36, "question": "Which operator is used to access members of a class in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 37, "question": "Which of the following is not a valid C++ data type?", "skill_id": 4, "skill": "C++"},
  {"id": 38, "question": "How do you create an object of a class in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 39, "question": "Which of the following is used to include external files in C++?", "skill_id": 4, "skill": "C++"},
  {"id": 40, "question": "Which of the following loops is present in C++?", "skill_id": 4, "skill": "C++"},

  {"id": 41, "question": "In C#, which data type would be most suitable for storing a large whole number?", "skill_id": 5, "skill": "C#"},
  {"id": 42, "question": "Which of the following is used to handle exceptions in C#?", "skill_id": 5, "skill": "C#"},
  {"id": 43, "question": "True or False: C# supports multi-threading.", "skill_id": 5, "skill": "C#"},
  {"id": 44, "question": "Which keyword is used to declare a constant in C#?", "skill_id": 5, "skill": "C#"},
  {"id": 45, "question": "How do you create an array in C#?", "skill_id": 5, "skill": "C#"},
  {"id": 46, "question": "Which of the following is a valid C# namespace?", "skill_id": 5, "skill": "C#"},
  {"id": 47, "question": "True or False: C# is case-sensitive.", "skill_id": 5, "skill": "C#"},
  {"id": 48, "question": "Which keyword is used to inherit a class in C#?", "skill_id": 5, "skill": "C#"},
  {"id": 49, "question": "Which of the following is a valid data type in C#?", "skill_id": 5, "skill": "C#"},
  {"id": 50, "question": "How do you handle file input/output in C#?", "skill_id": 5, "skill": "C#"},

  {"id": 51, "question": "Which of the following is not a valid Ruby data structure?", "skill_id": 6, "skill": "Ruby"},
  {"id": 52, "question": "Which method is used to iterate through an array in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 53, "question": "True or False: Ruby is a dynamically typed language.", "skill_id": 6, "skill": "Ruby"},
  {"id": 54, "question": "Which keyword is used to define a method in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 55, "question": "Which of the following is used to handle exceptions in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 56, "question": "How do you create a hash in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 57, "question": "Which of the following is a Ruby framework for web development?", "skill_id": 6, "skill": "Ruby"},
  {"id": 58, "question": "How do you print output in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 59, "question": "Which method is used to convert a string to an integer in Ruby?", "skill_id": 6, "skill": "Ruby"},
  {"id": 60, "question": "True or False: Ruby supports object-oriented programming.", "skill_id": 6, "skill": "Ruby"},

  {"id": 61, "question": "In SQL, what is the command to remove rows from a table?", "skill_id": 7, "skill": "SQL"},
  {"id": 62, "question": "Which SQL command is used to retrieve data from a database?", "skill_id": 7, "skill": "SQL"},
  {"id": 63, "question": "True or False: SQL supports transactions.", "skill_id": 7, "skill": "SQL"},
  {"id": 64, "question": "What is the function used to count the number of rows in a SQL query?", "skill_id": 7, "skill": "SQL"},
  {"id": 65, "question": "Which keyword is used to modify existing data in a table in SQL?", "skill_id": 7, "skill": "SQL"},
  {"id": 66, "question": "True or False: SQL is case-sensitive.", "skill_id": 7, "skill": "SQL"},
  {"id": 67, "question": "Which of the following is used to join tables in SQL?", "skill_id": 7, "skill": "SQL"},
  {"id": 68, "question": "Which SQL command is used to create a new table?", "skill_id": 7, "skill": "SQL"},
  {"id": 69, "question": "Which SQL clause is used to filter the results of a query?", "skill_id": 7, "skill": "SQL"},
  {"id": 70, "question": "True or False: SQL supports indexing.", "skill_id": 7, "skill": "SQL"},

  {"id": 71, "question": "True or False: Redis is an in-memory database.", "skill_id": 11, "skill": "Redis"},
  {"id": 72, "question": "Which data structure is natively supported by Redis?", "skill_id": 11, "skill": "Redis"},
  {"id": 73, "question": "Which command is used to store a key-value pair in Redis?", "skill_id": 11, "skill": "Redis"},
  {"id": 74, "question": "True or False: Redis can be used as a message broker.", "skill_id": 11, "skill": "Redis"},
  {"id": 75, "question": "Which command is used to delete a key in Redis?", "skill_id": 11, "skill": "Redis"},
  {"id": 76, "question": "Which type of data is persisted in Redis?", "skill_id": 11, "skill": "Redis"},
  {"id": 77, "question": "True or False: Redis supports transactions.", "skill_id": 11, "skill": "Redis"},

  {"id": 78, "question": "Which of the following is a primary feature of SQLite?", "skill_id": 12, "skill": "SQLite"},
  {"id": 79, "question": "True or False: SQLite is a serverless database.", "skill_id": 12, "skill": "SQLite"},
  {"id": 80, "question": "Which data type is not supported by SQLite?", "skill_id": 12, "skill": "SQLite"},
  {"id": 81, "question": "Which command is used to create a table in SQLite?", "skill_id": 12, "skill": "SQLite"},
  {"id": 82, "question": "True or False: SQLite does not support foreign keys.", "skill_id": 12, "skill": "SQLite"},
  {"id": 83, "question": "Which file extension is typically used for SQLite databases?", "skill_id": 12, "skill": "SQLite"},
  {"id": 84, "question": "Which of the following SQL commands is used to delete a row in SQLite?", "skill_id": 12, "skill": "SQLite"},

  {"id": 85, "question": "True or False: React.js is developed and maintained by Facebook.", "skill_id": 13, "skill": "React.js"},
  {"id": 86, "question": "Which of the following is a primary concept in React.js?", "skill_id": 13, "skill": "React.js"},
  {"id": 87, "question": "Which method is used to update the state in a functional React component?", "skill_id": 13, "skill": "React.js"},
  {"id": 88, "question": "True or False: React.js uses a virtual DOM to improve performance.", "skill_id": 13, "skill": "React.js"},
  {"id": 89, "question": "Which hook is used to handle side effects in React.js?", "skill_id": 13, "skill": "React.js"},
  {"id": 90, "question": "Which function is used to create a component in React.js?", "skill_id": 13, "skill": "React.js"},
  {"id": 91, "question": "True or False: React.js uses JSX to write components.", "skill_id": 13, "skill": "React.js"},

  {"id": 92, "question": "True or False: Vue.js is a progressive JavaScript framework.", "skill_id": 14, "skill": "Vue.js"},
  {"id": 93, "question": "Which of the following is a core feature of Vue.js?", "skill_id": 14, "skill": "Vue.js"},
  {"id": 94, "question": "Which directive is used for conditional rendering in Vue.js?", "skill_id": 14, "skill": "Vue.js"},
  {"id": 95, "question": "True or False: Vue.js supports two-way data binding.", "skill_id": 14, "skill": "Vue.js"},
  {"id": 96, "question": "Which command is used to create a new Vue.js project?", "skill_id": 14, "skill": "Vue.js"},
  {"id": 97, "question": "Which function is used to define a component in Vue.js?", "skill_id": 14, "skill": "Vue.js"},
  {"id": 98, "question": "True or False: Vue.js uses the virtual DOM.", "skill_id": 14, "skill": "Vue.js"},

  {"id": 99, "question": "True or False: Angular is a TypeScript-based framework.", "skill_id": 15, "skill": "Angular"},
  {"id": 100, "question": "Which of the following is a core module in Angular?", "skill_id": 15, "skill": "Angular"},
  {"id": 101, "question": "Which decorator is used to define a component in Angular?", "skill_id": 15, "skill": "Angular"},
  {"id": 102, "question": "True or False: Angular supports two-way data binding.", "skill_id": 15, "skill": "Angular"},
  {"id": 103, "question": "Which command is used to generate a new component in Angular?", "skill_id": 15, "skill": "Angular"},
  {"id": 104, "question": "Which file is used to define the root module in Angular?", "skill_id": 15, "skill": "Angular"},
  {"id": 105, "question": "True or False: Angular uses services for dependency injection.", "skill_id": 15, "skill": "Angular"},

  {"id": 106, "question": "True or False: Svelte is a JavaScript framework for building user interfaces.", "skill_id": 16, "skill": "Svelte"},
  {"id": 107, "question": "Which of the following is a key feature of Svelte?", "skill_id": 16, "skill": "Svelte"},
  {"id": 108, "question": "Which command is used to create a new Svelte project?", "skill_id": 16, "skill": "Svelte"},
  {"id": 109, "question": "True or False: Svelte compiles components into vanilla JavaScript.", "skill_id": 16, "skill": "Svelte"},
  {"id": 110, "question": "Which method is used to declare a reactive variable in Svelte?", "skill_id": 16, "skill": "Svelte"},
  {"id": 111, "question": "Which of the following is not a feature of Svelte?", "skill_id": 16, "skill": "Svelte"},
  {"id": 112, "question": "True or False: Svelte uses a virtual DOM.", "skill_id": 16, "skill": "Svelte"},

  {"id": 113, "question": "Which of the following is a core feature of Bootstrap?", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 114, "question": "True or False: Bootstrap is a CSS framework.", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 115, "question": "Which Bootstrap class is used for creating a responsive grid?", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 116, "question": "True or False: Bootstrap components are built using jQuery.", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 117, "question": "Which class is used to create a button in Bootstrap?", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 118, "question": "Which version of Bootstrap introduced the flexbox-based grid system?", "skill_id": 17, "skill": "Bootstrap"},
  {"id": 119, "question": "True or False: Bootstrap is a mobile-first framework.", "skill_id": 17, "skill": "Bootstrap"},

  {"id": 120, "question": "True or False: jQuery simplifies JavaScript DOM manipulation.", "skill_id": 18, "skill": "jQuery"},
  {"id": 121, "question": "Which jQuery method is used to hide an element?", "skill_id": 18, "skill": "jQuery"},
  {"id": 122, "question": "Which symbol is used to represent jQuery?", "skill_id": 18, "skill": "jQuery"},
  {"id": 123, "question": "True or False: jQuery is a JavaScript framework.", "skill_id": 18, "skill": "jQuery"},
  {"id": 124, "question": "Which method is used to add a class to an element in jQuery?", "skill_id": 18, "skill": "jQuery"},
  {"id": 125, "question": "Which method is used to perform an asynchronous HTTP request in jQuery?", "skill_id": 18, "skill": "jQuery"},
  {"id": 126, "question": "True or False: jQuery is no longer maintained.", "skill_id": 18, "skill": "jQuery"},
  {"id": 127, "question": "True or False: Node.js is a JavaScript runtime built on Chrome's V8 engine.", "skill_id": 19, "skill": "Node.js"},
  {"id": 128, "question": "Which module is used to create a server in Node.js?", "skill_id": 19, "skill": "Node.js"},
  {"id": 129, "question": "Which of the following is a core feature of Node.js?", "skill_id": 19, "skill": "Node.js"},
  {"id": 130, "question": "Which command is used to initialize a new Node.js project?", "skill_id": 19, "skill": "Node.js"},
  {"id": 131, "question": "Which of the following is a package manager for Node.js?", "skill_id": 19, "skill": "Node.js"},
  {"id": 132, "question": "True or False: Node.js supports non-blocking I/O operations.", "skill_id": 19, "skill": "Node.js"},
  {"id": 133, "question": "Which method is used to read a file in Node.js?", "skill_id": 19, "skill": "Node.js"},

  {"id": 134, "question": "True or False: Django is a Python web framework.", "skill_id": 20, "skill": "Django"},
  {"id": 135, "question": "Which of the following is a core feature of Django?", "skill_id": 20, "skill": "Django"},
  {"id": 136, "question": "Which command is used to create a new Django project?", "skill_id": 20, "skill": "Django"},
  {"id": 137, "question": "True or False: Django follows the Model-View-Template (MVT) pattern.", "skill_id": 20, "skill": "Django"},
  {"id": 138, "question": "Which command is used to start the development server in Django?", "skill_id": 20, "skill": "Django"},
  {"id": 139, "question": "Which file is used to define the database models in Django?", "skill_id": 20, "skill": "Django"},
  {"id": 140, "question": "True or False: Django supports Object-Relational Mapping (ORM).", "skill_id": 20, "skill": "Django"},

  {"id": 141, "question": "True or False: Spring Boot is a Java-based framework.", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 142, "question": "Which of the following is a core feature of Spring Boot?", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 143, "question": "Which annotation is used to define a Spring Boot application?", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 144, "question": "Which command is used to run a Spring Boot application?", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 145, "question": "Which of the following is a dependency injection framework in Spring Boot?", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 146, "question": "True or False: Spring Boot supports microservices architecture.", "skill_id": 21, "skill": "Spring Boot"},
  {"id": 147, "question": "Which file is used to configure application properties in Spring Boot?", "skill_id": 21, "skill": "Spring Boot"},

  {"id": 148, "question": "True or False: Express.js is a web framework for Node.js.", "skill_id": 22, "skill": "Express.js"},
  {"id": 149, "question": "Which method is used to create a new Express.js application?", "skill_id": 22, "skill": "Express.js"},
  {"id": 150, "question": "Which of the following is a core feature of Express.js?", "skill_id": 22, "skill": "Express.js"},
  {"id": 151, "question": "Which middleware is used to handle HTTP requests in Express.js?", "skill_id": 22, "skill": "Express.js"},
  {"id": 152, "question": "Which command is used to install Express.js?", "skill_id": 22, "skill": "Express.js"},
  {"id": 153, "question": "True or False: Express.js supports routing.", "skill_id": 22, "skill": "Express.js"},
  {"id": 154, "question": "Which method is used to listen to incoming requests in Express.js?", "skill_id": 22, "skill": "Express.js"},

  {"id": 155, "question": "True or False: Ruby on Rails is a server-side web application framework.", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 156, "question": "Which of the following is a core feature of Ruby on Rails?", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 157, "question": "Which command is used to create a new Rails project?", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 158, "question": "True or False: Rails follows the Model-View-Controller (MVC) pattern.", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 159, "question": "Which command is used to generate a model in Rails?", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 160, "question": "Which file is used to configure routes in Rails?", "skill_id": 23, "skill": "Ruby on Rails"},
  {"id": 161, "question": "True or False: Ruby on Rails supports Object-Relational Mapping (ORM).", "skill_id": 23, "skill": "Ruby on Rails"},

  {"id": 162, "question": "True or False: Flask is a lightweight Python web framework.", "skill_id": 24, "skill": "Flask"},
  {"id": 163, "question": "Which command is used to install Flask?", "skill_id": 24, "skill": "Flask"},
  {"id": 164, "question": "Which of the following is a core feature of Flask?", "skill_id": 24, "skill": "Flask"},
  {"id": 165, "question": "Which method is used to run a Flask application?", "skill_id": 24, "skill": "Flask"},
  {"id": 166, "question": "True or False: Flask is based on the Werkzeug toolkit.", "skill_id": 24, "skill": "Flask"},
  {"id": 167, "question": "Which command is used to start the development server in Flask?", "skill_id": 24, "skill": "Flask"},
  {"id": 168, "question": "Which file is used to define routes in Flask?", "skill_id": 24, "skill": "Flask"},

  {"id": 169, "question": "True or False: Git is a distributed version control system.", "skill_id": 25, "skill": "Git"},
  {"id": 170, "question": "Which command is used to initialize a new Git repository?", "skill_id": 25, "skill": "Git"},
  {"id": 171, "question": "Which of the following is a core feature of Git?", "skill_id": 25, "skill": "Git"},
  {"id": 172, "question": "Which command is used to clone a repository in Git?", "skill_id": 25, "skill": "Git"},
  {"id": 173, "question": "Which command is used to commit changes in Git?", "skill_id": 25, "skill": "Git"},
  {"id": 174, "question": "True or False: Git supports branching.", "skill_id": 25, "skill": "Git"},
  {"id": 175, "question": "Which command is used to merge branches in Git?", "skill_id": 25, "skill": "Git"},

  {"id": 176, "question": "True or False: GitHub is a platform for hosting Git repositories.", "skill_id": 26, "skill": "GitHub"},
  {"id": 177, "question": "Which command is used to push changes to GitHub?", "skill_id": 26, "skill": "GitHub"},
  {"id": 178, "question": "Which of the following is a core feature of GitHub?", "skill_id": 26, "skill": "GitHub"},
  {"id": 179, "question": "Which file is used to define workflows in GitHub Actions?", "skill_id": 26, "skill": "GitHub"},
  {"id": 180, "question": "Which of the following is used to submit changes for review in GitHub?", "skill_id": 26, "skill": "GitHub"},
  {"id": 181, "question": "True or False: GitHub supports private repositories.", "skill_id": 26, "skill": "GitHub"},
  {"id": 182, "question": "Which command is used to fork a repository in GitHub?", "skill_id": 26, "skill": "GitHub"},

  {"id": 183, "question": "True or False: Bitbucket is a Git repository hosting service.", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 184, "question": "Which command is used to create a pull request in Bitbucket?", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 185, "question": "Which of the following is a core feature of Bitbucket?", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 186, "question": "True or False: Bitbucket supports continuous integration (CI).", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 187, "question": "Which command is used to clone a repository in Bitbucket?", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 188, "question": "Which of the following is used to define pipelines in Bitbucket?", "skill_id": 28, "skill": "Bitbucket"},
  {"id": 189, "question": "True or False: Bitbucket supports Mercurial repositories.", "skill_id": 28, "skill": "Bitbucket"},

  {"id": 190, "question": "True or False: Agile methodologies focus on iterative development.", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 191, "question": "Which of the following is a key principle of Agile?", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 192, "question": "Which Agile methodology framework uses time-boxed sprints?", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 193, "question": "True or False: Agile encourages customer collaboration.", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 194, "question": "Which of the following is not a part of the Agile Manifesto?", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 195, "question": "Which of the following roles is typically part of an Agile team?", "skill_id": 31, "skill": "Agile Methodologies"},
  {"id": 196, "question": "True or False: Agile focuses on responding to change over following a plan.", "skill_id": 31, "skill": "Agile Methodologies"},

  {"id": 197, "question": "True or False: Scrum is a framework for managing work in Agile projects.", "skill_id": 32, "skill": "Scrum"},
  {"id": 198, "question": "Which role in Scrum is responsible for maximizing product value?", "skill_id": 32, "skill": "Scrum"},
  {"id": 199, "question": "Which Scrum event involves reviewing the product increment?", "skill_id": 32, "skill": "Scrum"},
  {"id": 200, "question": "True or False: Sprints in Scrum are time-boxed iterations.", "skill_id": 32, "skill": "Scrum"},
  {"id": 201, "question": "Which artifact in Scrum contains the list of all desired work on the product?", "skill_id": 32, "skill": "Scrum"},
  {"id": 202, "question": "Which event in Scrum is held daily for team synchronization?", "skill_id": 32, "skill": "Scrum"},
  {"id": 203, "question": "True or False: The Scrum Master is responsible for removing impediments.", "skill_id": 32, "skill": "Scrum"},

  {"id": 204, "question": "True or False: Continuous Integration aims to detect integration bugs early.", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 205, "question": "Which tool is commonly used for Continuous Integration?", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 206, "question": "What is the primary goal of Continuous Integration?", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 207, "question": "True or False: Automated testing is a key practice in Continuous Integration.", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 208, "question": "Which practice complements Continuous Integration by automating deployments?", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 209, "question": "Which of the following is a benefit of Continuous Integration?", "skill_id": 34, "skill": "Continuous Integration"},
  {"id": 210, "question": "True or False: Continuous Integration encourages frequent code commits.", "skill_id": 34, "skill": "Continuous Integration"},

  {"id": 211, "question": "True or False: Docker is a platform for containerization.", "skill_id": 37, "skill": "Docker"},
  {"id": 212, "question": "Which command is used to build a Docker image?", "skill_id": 37, "skill": "Docker"},
  {"id": 213, "question": "Which file is used to define a Docker image?", "skill_id": 37, "skill": "Docker"},
  {"id": 214, "question": "True or False: Docker containers are lightweight and portable.", "skill_id": 37, "skill": "Docker"},
  {"id": 215, "question": "Which command is used to start a Docker container?", "skill_id": 37, "skill": "Docker"},
  {"id": 216, "question": "Which of the following is a Docker container orchestration tool?", "skill_id": 37, "skill": "Docker"},
  {"id": 217, "question": "True or False: Docker uses a layered file system for images.", "skill_id": 37, "skill": "Docker"},

  {"id": 218, "question": "True or False: Kubernetes is a platform for container orchestration.", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 219, "question": "Which of the following is a key component in Kubernetes architecture?", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 220, "question": "Which command-line tool is used to interact with Kubernetes clusters?", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 221, "question": "True or False: Kubernetes can automatically scale containers.", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 222, "question": "Which Kubernetes object represents a group of containers?", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 223, "question": "Which of the following is used to manage storage in Kubernetes?", "skill_id": 38, "skill": "Kubernetes"},
  {"id": 224, "question": "True or False: Kubernetes can manage networking between containers.", "skill_id": 38, "skill": "Kubernetes"},

  {"id": 225, "question": "True or False: OpenShift is built on Kubernetes.", "skill_id": 39, "skill": "OpenShift"},
  {"id": 226, "question": "Which of the following is a feature of OpenShift?", "skill_id": 39, "skill": "OpenShift"},
  {"id": 227, "question": "Which command-line tool is used to interact with OpenShift?", "skill_id": 39, "skill": "OpenShift"},
  {"id": 228, "question": "True or False: OpenShift includes an integrated developer environment.", "skill_id": 39, "skill": "OpenShift"},
  {"id": 229, "question": "Which of the following is a component of OpenShift's architecture?", "skill_id": 39, "skill": "OpenShift"},
  {"id": 230, "question": "Which type of application is commonly deployed using OpenShift?", "skill_id": 39, "skill": "OpenShift"},
  {"id": 231, "question": "True or False: OpenShift provides enterprise-grade security.", "skill_id": 39, "skill": "OpenShift"},

  {"id": 232, "question": "True or False: AWS is a cloud computing platform.", "skill_id": 40, "skill": "AWS"},
  {"id": 233, "question": "Which service in AWS is used for computing power?", "skill_id": 40, "skill": "AWS"},
  {"id": 234, "question": "Which of the following is a storage service in AWS?", "skill_id": 40, "skill": "AWS"},
  {"id": 235, "question": "True or False: AWS offers serverless computing.", "skill_id": 40, "skill": "AWS"},
  {"id": 236, "question": "Which service in AWS is used for database management?", "skill_id": 40, "skill": "AWS"},
  {"id": 237, "question": "Which AWS service is used for content delivery?", "skill_id": 40, "skill": "AWS"},
  {"id": 238, "question": "True or False: AWS provides multi-region availability for its services.", "skill_id": 40, "skill": "AWS"},

  {"id": 239, "question": "True or False: Terraform is an Infrastructure-as-Code (IaC) tool.", "skill_id": 43, "skill": "Terraform"},
  {"id": 240, "question": "Which language is used to define infrastructure in Terraform?", "skill_id": 43, "skill": "Terraform"},
  {"id": 241, "question": "Which command is used to initialize a Terraform project?", "skill_id": 43, "skill": "Terraform"},
  {"id": 242, "question": "True or False: Terraform can manage multi-cloud environments.", "skill_id": 43, "skill": "Terraform"},
  {"id": 243, "question": "Which command is used to apply infrastructure changes in Terraform?", "skill_id": 43, "skill": "Terraform"},
  {"id": 244, "question": "Which of the following is a benefit of using Terraform?", "skill_id": 43, "skill": "Terraform"},
  {"id": 245, "question": "True or False: Terraform stores the state of infrastructure in a state file.", "skill_id": 43, "skill": "Terraform"},

  {"id": 246, "question": "True or False: Ansible is an open-source automation tool.", "skill_id": 44, "skill": "Ansible"},
  {"id": 247, "question": "Which language is used to write playbooks in Ansible?", "skill_id": 44, "skill": "Ansible"},
  {"id": 248, "question": "Which command is used to execute a playbook in Ansible?", "skill_id": 44, "skill": "Ansible"},
  {"id": 249, "question": "True or False: Ansible supports agentless architecture.", "skill_id": 44, "skill": "Ansible"},
  {"id": 250, "question": "Which of the following is a key component of Ansible?", "skill_id": 44, "skill": "Ansible"},
  {"id": 251, "question": "Which of the following is used to define tasks in Ansible?", "skill_id": 44, "skill": "Ansible"},
  {"id": 252, "question": "True or False: Ansible can manage both Linux and Windows systems.", "skill_id": 44, "skill": "Ansible"},

  {"id": 253, "question": "True or False: Unit testing focuses on testing individual components.", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 254, "question": "Which of the following is a commonly used framework for unit testing?", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 255, "question": "What is the primary goal of unit testing?", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 256, "question": "True or False: Unit tests are typically automated.", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 257, "question": "Which of the following is a best practice in unit testing?", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 258, "question": "Which tool is commonly used for code coverage in unit testing?", "skill_id": 45, "skill": "Unit Testing"},
  {"id": 259, "question": "True or False: Unit testing helps in identifying defects early in development.", "skill_id": 45, "skill": "Unit Testing"},

  {"id": 260, "question": "True or False: Integration testing focuses on the interaction between components.", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 261, "question": "Which of the following is a primary goal of integration testing?", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 262, "question": "Which testing phase usually follows integration testing?", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 263, "question": "True or False: Integration tests are typically more complex than unit tests.", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 264, "question": "Which of the following is not a type of integration testing?", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 265, "question": "Which tool is commonly used for integration testing in Java?", "skill_id": 46, "skill": "Integration Testing"},
  {"id": 266, "question": "True or False: Integration testing is a part of the verification process.", "skill_id": 46, "skill": "Integration Testing"},

  {"id": 267, "question": "True or False: End-to-end testing validates the entire application flow.", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 268, "question": "Which of the following is a common challenge in end-to-end testing?", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 269, "question": "Which tool is commonly used for end-to-end testing?", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 270, "question": "True or False: End-to-end tests cover both frontend and backend systems.", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 271, "question": "Which testing strategy often includes end-to-end testing?", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 272, "question": "Which of the following is a benefit of end-to-end testing?", "skill_id": 47, "skill": "End-to-End Testing"},
  {"id": 273, "question": "True or False: End-to-end testing is typically the last phase before production release.", "skill_id": 47, "skill": "End-to-End Testing"},

  {"id": 274, "question": "True or False: Selenium is a tool for automating web browser interactions.", "skill_id": 48, "skill": "Selenium"},
  {"id": 275, "question": "Which language is supported by Selenium WebDriver?", "skill_id": 48, "skill": "Selenium"},
  {"id": 276, "question": "Which of the following is a component of the Selenium suite?", "skill_id": 48, "skill": "Selenium"},
  {"id": 277, "question": "True or False: Selenium supports parallel test execution.", "skill_id": 48, "skill": "Selenium"},
  {"id": 278, "question": "Which browser is not supported by Selenium WebDriver?", "skill_id": 48, "skill": "Selenium"},
  {"id": 279, "question": "Which method is used in Selenium to find elements by CSS selector?", "skill_id": 48, "skill": "Selenium"},
  {"id": 280, "question": "True or False: Selenium Grid is used for running tests on multiple machines.", "skill_id": 48, "skill": "Selenium"},

  {"id": 281, "question": "True or False: Jest is a testing framework for JavaScript.", "skill_id": 49, "skill": "Jest"},
  {"id": 282, "question": "Which feature of Jest allows tests to be run in parallel?", "skill_id": 49, "skill": "Jest"},
  {"id": 283, "question": "Which command is used to run tests with Jest?", "skill_id": 49, "skill": "Jest"},
  {"id": 284, "question": "True or False: Jest supports snapshot testing.", "skill_id": 49, "skill": "Jest"},
  {"id": 285, "question": "Which of the following is a commonly used assertion library with Jest?", "skill_id": 49, "skill": "Jest"},
  {"id": 286, "question": "Which feature of Jest is used for mocking modules?", "skill_id": 49, "skill": "Jest"},
  {"id": 287, "question": "True or False: Jest is commonly used for testing React applications.", "skill_id": 49, "skill": "Jest"},

  {"id": 288, "question": "True or False: RESTful APIs follow a stateless architecture.", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 289, "question": "Which HTTP method is used to create a resource in a RESTful API?", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 290, "question": "Which of the following is a constraint of REST architecture?", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 291, "question": "True or False: RESTful APIs are commonly used for web services.", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 292, "question": "Which status code represents a successful GET request in RESTful APIs?", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 293, "question": "Which tool is commonly used to test RESTful APIs?", "skill_id": 51, "skill": "RESTful APIs"},
  {"id": 294, "question": "True or False: RESTful APIs rely on a single communication protocol.", "skill_id": 51, "skill": "RESTful APIs"},

  {"id": 295, "question": "True or False: GraphQL allows clients to specify the shape of the response.", "skill_id": 52, "skill": "GraphQL"},
  {"id": 296, "question": "Which of the following is a key feature of GraphQL?", "skill_id": 52, "skill": "GraphQL"},
  {"id": 297, "question": "Which query language is used by GraphQL to fetch data?", "skill_id": 52, "skill": "GraphQL"},
  {"id": 298, "question": "True or False: GraphQL queries are performed using the HTTP protocol.", "skill_id": 52, "skill": "GraphQL"},
  {"id": 299, "question": "Which command is used to define a GraphQL schema?", "skill_id": 52, "skill": "GraphQL"},
  {"id": 300, "question": "Which of the following is an advantage of GraphQL over REST?", "skill_id": 52, "skill": "GraphQL"},
  {"id": 301, "question": "True or False: GraphQL can replace REST for API development.", "skill_id": 52, "skill": "GraphQL"},

  {"id": 302, "question": "True or False: WebSockets enable two-way communication between client and server.", "skill_id": 55, "skill": "WebSockets"},
  {"id": 303, "question": "Which protocol does WebSockets operate over?", "skill_id": 55, "skill": "WebSockets"},
  {"id": 304, "question": "Which of the following is a common use case for WebSockets?", "skill_id": 55, "skill": "WebSockets"},
  {"id": 305, "question": "True or False: WebSocket connections remain open after the handshake.", "skill_id": 55, "skill": "WebSockets"},
  {"id": 306, "question": "Which status code is returned when a WebSocket connection is closed?", "skill_id": 55, "skill": "WebSockets"},
  {"id": 307, "question": "Which of the following libraries is commonly used to implement WebSockets?", "skill_id": 55, "skill": "WebSockets"},
  {"id": 308, "question": "True or False: WebSockets are typically used for real-time applications.", "skill_id": 55, "skill": "WebSockets"},

  {"id": 309, "question": "True or False: OAuth is used for authorization.", "skill_id": 56, "skill": "OAuth"},
  {"id": 310, "question": "Which of the following is a key component of OAuth?", "skill_id": 56, "skill": "OAuth"},
  {"id": 311, "question": "Which version of OAuth is widely used today?", "skill_id": 56, "skill": "OAuth"},
  {"id": 312, "question": "True or False: OAuth allows third-party applications to access user data securely.", "skill_id": 56, "skill": "OAuth"},
  {"id": 313, "question": "Which HTTP method is commonly used to request an OAuth access token?", "skill_id": 56, "skill": "OAuth"},
  {"id": 314, "question": "Which of the following is a common use case for OAuth?", "skill_id": 56, "skill": "OAuth"},
  {"id": 315, "question": "True or False: OAuth is only used for user authentication.", "skill_id": 56, "skill": "OAuth"},

  {"id": 316, "question": "True or False: Microservices architecture allows independent deployment of services.", "skill_id": 57, "skill": "Microservices"},
  {"id": 317, "question": "Which of the following is a benefit of microservices architecture?", "skill_id": 57, "skill": "Microservices"},
  {"id": 318, "question": "Which of the following is a challenge in implementing microservices?", "skill_id": 57, "skill": "Microservices"},
  {"id": 319, "question": "True or False: Microservices architecture supports continuous delivery.", "skill_id": 57, "skill": "Microservices"},
  {"id": 320, "question": "Which of the following is commonly used to manage microservices?", "skill_id": 57, "skill": "Microservices"},
  {"id": 321, "question": "Which communication protocol is often used in microservices?", "skill_id": 57, "skill": "Microservices"},
  {"id": 322, "question": "True or False: Microservices can be scaled independently.", "skill_id": 57, "skill": "Microservices"},

  {"id": 323, "question": "True or False: Monolithic architecture is characterized by a single codebase.", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 324, "question": "Which of the following is a disadvantage of monolithic architecture?", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 325, "question": "Which type of application is typically built using monolithic architecture?", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 326, "question": "True or False: Scaling a monolithic architecture usually requires scaling the entire system.", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 327, "question": "Which of the following is an advantage of monolithic architecture?", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 328, "question": "Which of the following is often a challenge with monolithic applications?", "skill_id": 58, "skill": "Monolithic Architecture"},
  {"id": 329, "question": "True or False: Monolithic architectures are difficult to deploy in a continuous delivery pipeline.", "skill_id": 58, "skill": "Monolithic Architecture"},

  {"id": 330, "question": "True or False: Service-Oriented Architecture (SOA) focuses on reusable services.", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 331, "question": "Which of the following is a core principle of SOA?", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 332, "question": "Which communication protocol is commonly used in SOA?", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 333, "question": "True or False: SOA supports service composition.", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 334, "question": "Which of the following is an advantage of SOA?", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 335, "question": "Which of the following is a common challenge in SOA?", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"},
  {"id": 336, "question": "True or False: SOA typically uses tightly coupled services.", "skill_id": 60, "skill": "Service-Oriented Architecture (SOA)"}


]